#pragma once

#include <cstdint>

enum eEntityType : uint8_t
{
	ENTITY_TYPE_NOTHING,
	ENTITY_TYPE_BUILDING,
	ENTITY_TYPE_ANIMATED_BUILDING,
	ENTITY_TYPE_VEHICLE,
	ENTITY_TYPE_PED,
	ENTITY_TYPE_OBJECT,
	ENTITY_TYPE_DUMMY_OBJECT,
	ENTITY_TYPE_PORTAL,
	ENTITY_TYPE_MLO,
	ENTITY_TYPE_NOTINPOOLS,
	ENTITY_TYPE_PARTICLESYSTEM,
	ENTITY_TYPE_LIGHT,
	ENTITY_TYPE_COMPOSITE,
	ENTITY_TYPE_INSTANCE_LIST,
	ENTITY_TYPE_GRASS_INSTANCE_LIST,
	ENTITY_TYPE_VEHICLEGLASSCOMPONENT,

	ENTITY_TYPE_TOTAL
};
