#pragma once

#include <cstdint>

namespace Stand
{
    enum TransitionState : uint8_t
    {
        TRANSITION_STATE_EMPTY = 0,
        TRANSITION_STATE_SP_SWOOP_UP = 1,
        TRANSITION_STATE_MP_SWOOP_UP = 2,
        TRANSITION_STATE_CREATOR_SWOOP_UP = 3,
        TRANSITION_STATE_PRE_HUD_CHECKS = 4,
        TRANSITION_STATE_WAIT_HUD_EXIT = 5,
        TRANSITION_STATE_SP_SWOOP_DOWN = 7,
        TRANSITION_STATE_MP_SWOOP_DOWN = 8,
        TRANSITION_STATE_WAIT_FOR_SUMMON = 6,
        TRANSITION_STATE_CANCEL_JOINING = 9,
        TRANSITION_STATE_WAIT_ON_INVITE = 15,
        TRANSITION_STATE_PRE_FM_LAUNCH_SCRIPT = 22,
        TRANSITION_STATE_FM_TRANSITION_CREATE_PLAYER = 25,
        TRANSITION_STATE_FM_SWOOP_DOWN = 27,
        TRANSITION_STATE_RETURN_TO_SINGLEPLAYER = 63,
        TRANSITION_STATE_WAIT_FOR_SINGLEPLAYER_TO_START = 64,
    };
}
