#include "Commands/Self/CommandTabTransform.hpp"

#include "Core/LogHelper.hpp"
#include "Util/Joaat.hpp"

#include <string>

namespace Stand
{
	namespace
	{
		struct ModelEntry
		{
			const char* label;
			const char* model;
		};

		constexpr ModelEntry kPlayable[] = {
			{"Michael De Santa",  "player_zero"},
			{"Franklin Clinton",  "player_one"},
			{"Trevor Philips",    "player_two"},
			{"MP Male",           "mp_m_freemode_01"},
			{"MP Female",         "mp_f_freemode_01"},
		};

		constexpr ModelEntry kGroundAnimals[] = {
			{"Boar",                 "a_c_boar"},
			{"Cat",                  "a_c_cat_01"},
			{"Chimpanzee",           "a_c_chimp"},
			{"Chop",                 "a_c_chop"},
			{"Cow",                  "a_c_cow"},
			{"Coyote",               "a_c_coyote"},
			{"Deer",                 "a_c_deer"},
			{"Dog",                  "a_c_dog"},
			{"Hen",                  "a_c_hen"},
			{"Horse (Bay)",          "a_c_horse_01"},
			{"Horse (Chestnut)",     "a_c_horse_02"},
			{"Horse (Piebald)",      "a_c_horse_03"},
			{"Horse (Roan)",         "a_c_horse_04"},
			{"Horse (Grey)",         "a_c_horse_05"},
			{"Husky",                "a_c_husky"},
			{"Mountain Lion",        "a_c_mtlion"},
			{"Pig",                  "a_c_pig"},
			{"Poodle",               "a_c_poodle"},
			{"Pug",                  "a_c_pug"},
			{"Rabbit",               "a_c_rabbit_01"},
			{"Rat",                  "a_c_rat"},
			{"Retriever",            "a_c_retriever"},
			{"Rhesus Macaque",       "a_c_rhesus"},
			{"Rottweiler",           "a_c_rottweiler"},
			{"German Shepherd",      "a_c_shepherd"},
			{"Skunk",                "a_c_skunk"},
			{"Wampus Cat",           "a_c_wampus"},
			{"West Highland Terrier","a_c_westy"},
			{"Panther",              "a_c_panther"},
			{"Lion",                 "a_c_lion"},
			{"Wolf",                 "a_c_wolf"},
			{"Elk",                  "a_c_elk"},
			{"Jack Russell Terrier", "a_c_hick_chicken"},
		};

		constexpr ModelEntry kWaterAnimals[] = {
			{"Dolphin",           "a_c_dolphin"},
			{"Fish",              "a_c_fish"},
			{"Killer Whale",      "a_c_killerwhale"},
			{"Bull Shark",        "a_c_shark_bull"},
			{"Hammerhead Shark",  "a_c_shark_hammerhead"},
			{"Tiger Shark",       "a_c_shark_tiger"},
			{"Stingray",          "a_c_stingray"},
		};

		constexpr ModelEntry kFlyingAnimals[] = {
			{"Hawk",      "a_c_chickenhawk"},
			{"Cormorant", "a_c_cormorant"},
			{"Crow",      "a_c_crow"},
			{"Pigeon",    "a_c_pigeon"},
			{"Seagull",   "a_c_seagull"},
		};

		constexpr const char* kNPCModels[] = {
			// Ambient Male Middle-Age
			"a_m_m_acult_01",
			"a_m_m_afriamer_01",
			"a_m_m_beach_01",
			"a_m_m_beach_02",
			"a_m_m_bevhills_01",
			"a_m_m_bevhills_02",
			"a_m_m_business_01",
			"a_m_m_business_02",
			"a_m_m_eastsa_01",
			"a_m_m_eastsa_02",
			"a_m_m_farmer_01",
			"a_m_m_fatbla_01",
			"a_m_m_fatcult_01",
			"a_m_m_fatwhite_01",
			"a_m_m_genfat_01",
			"a_m_m_genfat_02",
			"a_m_m_golfer_01",
			"a_m_m_hasjew_01",
			"a_m_m_hillbilly_01",
			"a_m_m_hillbilly_02",
			"a_m_m_indian_01",
			"a_m_m_ktown_01",
			"a_m_m_ktown_02",
			"a_m_m_malibu_01",
			"a_m_m_mexcntry_01",
			"a_m_m_mexlabor_01",
			"a_m_m_og_boss_01",
			"a_m_m_paparazzi_01",
			"a_m_m_polynesian_01",
			"a_m_m_prolhost_01",
			"a_m_m_rurmeth_01",
			"a_m_m_salton_01",
			"a_m_m_salton_02",
			"a_m_m_salton_03",
			"a_m_m_salton_04",
			"a_m_m_salton2_01",
			"a_m_m_salton2_02",
			"a_m_m_salton2_03",
			"a_m_m_salton2_04",
			"a_m_m_salton3_01",
			"a_m_m_skater_01",
			"a_m_m_skidrow_01",
			"a_m_m_socenlat_01",
			"a_m_m_soucentmc_01",
			"a_m_m_stlat_02",
			"a_m_m_tennis_01",
			"a_m_m_tourist_01",
			"a_m_m_trampbeac_01",
			"a_m_m_trampbeac_02",
			"a_m_m_tramp_01",
			"a_m_m_tranvest_01",
			"a_m_m_tranvest_02",
			// Ambient Male Old
			"a_m_o_acult_01",
			"a_m_o_acult_02",
			"a_m_o_beach_01",
			"a_m_o_bevhills_01",
			"a_m_o_bevhills_02",
			"a_m_o_genstreet_01",
			"a_m_o_ktown_01",
			"a_m_o_salton_01",
			"a_m_o_soucent_01",
			"a_m_o_soucent_02",
			"a_m_o_soucent_03",
			"a_m_o_tramp_01",
			// Ambient Male Young
			"a_m_y_acult_01",
			"a_m_y_acult_02",
			"a_m_y_beach_01",
			"a_m_y_beach_02",
			"a_m_y_beach_03",
			"a_m_y_beachvesp_01",
			"a_m_y_beachvesp_02",
			"a_m_y_bevhills_01",
			"a_m_y_bevhills_02",
			"a_m_y_bevhills_03",
			"a_m_y_bevhills_04",
			"a_m_y_breakdance_01",
			"a_m_y_busicas_01",
			"a_m_y_business_01",
			"a_m_y_business_02",
			"a_m_y_business_03",
			"a_m_y_clubcust_01",
			"a_m_y_clubcust_02",
			"a_m_y_clubcust_03",
			"a_m_y_clubcust_04",
			"a_m_y_dhill_01",
			"a_m_y_downtown_01",
			"a_m_y_eastsa_01",
			"a_m_y_eastsa_02",
			"a_m_y_epsilon_01",
			"a_m_y_epsilon_02",
			"a_m_y_fat_01",
			"a_m_y_fireman_01",
			"a_m_y_gencaspat_01",
			"a_m_y_genstreet_01",
			"a_m_y_genstreet_02",
			"a_m_y_golfer_01",
			"a_m_y_hasjew_01",
			"a_m_y_hasjew_02",
			"a_m_y_hiker_01",
			"a_m_y_hippy_01",
			"a_m_y_hipster_01",
			"a_m_y_hipster_02",
			"a_m_y_hipster_03",
			"a_m_y_hipster_04",
			"a_m_y_indian_01",
			"a_m_y_jetski_01",
			"a_m_y_juggalo_01",
			"a_m_y_ktown_01",
			"a_m_y_ktown_02",
			"a_m_y_latino_01",
			"a_m_y_methhead_01",
			"a_m_y_mexthug_01",
			"a_m_y_motox_01",
			"a_m_y_motox_02",
			"a_m_y_musclbeac_01",
			"a_m_y_musclbeac_02",
			"a_m_y_polynesian_01",
			"a_m_y_roadcyc_01",
			"a_m_y_runner_01",
			"a_m_y_runner_02",
			"a_m_y_rurmeth_01",
			"a_m_y_salton_01",
			"a_m_y_skater_01",
			"a_m_y_skater_02",
			"a_m_y_skater_03",
			"a_m_y_skidrow_01",
			"a_m_y_skidrow_02",
			"a_m_y_soucent_01",
			"a_m_y_soucent_02",
			"a_m_y_soucent_03",
			"a_m_y_soucent_04",
			"a_m_y_stbla_01",
			"a_m_y_stbla_02",
			"a_m_y_stlat_01",
			"a_m_y_stwhi_01",
			"a_m_y_stwhi_02",
			"a_m_y_sunbathe_01",
			"a_m_y_surfer_01",
			"a_m_y_surfer_02",
			"a_m_y_triathlon_01",
			// Ambient Female Middle-Age
			"a_f_m_beach_01",
			"a_f_m_bevhills_01",
			"a_f_m_bevhills_02",
			"a_f_m_bodybuild_01",
			"a_f_m_business_02",
			"a_f_m_downtown_01",
			"a_f_m_eastsa_01",
			"a_f_m_eastsa_02",
			"a_f_m_fatbla_01",
			"a_f_m_fatbla_02",
			"a_f_m_fat_01",
			"a_f_m_genstreet_01",
			"a_f_m_genstreet_02",
			"a_f_m_golfer_01",
			"a_f_m_hipster_01",
			"a_f_m_hipster_02",
			"a_f_m_hipster_03",
			"a_f_m_hipster_04",
			"a_f_m_indian_01",
			"a_f_m_ktown_01",
			"a_f_m_ktown_02",
			"a_f_m_prolhost_01",
			"a_f_m_prolhost_02",
			"a_f_m_rurmeth_01",
			"a_f_m_salton_01",
			"a_f_m_skidrow_01",
			"a_f_m_socenlat_01",
			"a_f_m_soucentmc_01",
			"a_f_m_soucent_01",
			"a_f_m_soucent_02",
			"a_f_m_tourist_01",
			"a_f_m_tourist_02",
			"a_f_m_trampbeac_01",
			"a_f_m_tramp_01",
			// Ambient Female Old
			"a_f_o_genstreet_01",
			"a_f_o_genstreet_02",
			"a_f_o_indian_01",
			"a_f_o_ktown_01",
			"a_f_o_salton_01",
			"a_f_o_soucent_01",
			"a_f_o_soucent_02",
			"a_f_o_soucent_03",
			"a_f_o_soucent_04",
			// Ambient Female Young
			"a_f_y_beach_01",
			"a_f_y_beach_02",
			"a_f_y_beach_03",
			"a_f_y_beachvesp_01",
			"a_f_y_beachvesp_02",
			"a_f_y_bevhills_01",
			"a_f_y_bevhills_02",
			"a_f_y_clubcust_01",
			"a_f_y_clubcust_02",
			"a_f_y_clubcust_03",
			"a_f_y_clubcust_04",
			"a_f_y_downtown_01",
			"a_f_y_eastsa_01",
			"a_f_y_epsilon_01",
			"a_f_y_fitness_01",
			"a_f_y_fitness_02",
			"a_f_y_gencaspat_01",
			"a_f_y_genstreet_01",
			"a_f_y_genstreet_02",
			"a_f_y_golfer_01",
			"a_f_y_hipster_01",
			"a_f_y_hipster_02",
			"a_f_y_hipster_03",
			"a_f_y_hipster_04",
			"a_f_y_indian_01",
			"a_f_y_indian_02",
			"a_f_y_juggalo_01",
			"a_f_y_ktown_01",
			"a_f_y_ktown_02",
			"a_f_y_latino_01",
			"a_f_y_mistress_01",
			"a_f_y_polynesian_01",
			"a_f_y_runner_01",
			"a_f_y_rurmeth_01",
			"a_f_y_salton_01",
			"a_f_y_skater_01",
			"a_f_y_socenlat_01",
			"a_f_y_soucent_01",
			"a_f_y_soucent_02",
			"a_f_y_soucent_03",
			"a_f_y_stlat_01",
			"a_f_y_stwhi_01",
			"a_f_y_stwhi_02",
			"a_f_y_sunbathe_01",
			"a_f_y_surfer_01",
			"a_f_y_topless_01",
			"a_f_y_triathlon_01",
			"a_f_y_yoga_01",
			// Gang Male Middle-Age
			"g_m_m_armgoon_01",
			"g_m_m_chemwork_01",
			"g_m_m_chibos_01",
			"g_m_m_chibos_02",
			"g_m_m_chicold_01",
			"g_m_m_chicold_02",
			"g_m_m_chinese_01",
			"g_m_m_chinese_02",
			"g_m_m_eastsa_01",
			"g_m_m_famca_01",
			"g_m_m_famga_01",
			"g_m_m_fammc_01",
			"g_m_m_fammc_02",
			"g_m_m_ktown_01",
			"g_m_m_ktown_02",
			"g_m_m_lost_01",
			"g_m_m_lost_02",
			"g_m_m_lost_03",
			"g_m_m_mexboss_01",
			"g_m_m_mexboss_02",
			"g_m_m_mexgoon_01",
			"g_m_m_mexgoon_02",
			"g_m_m_mexgoon_03",
			"g_m_m_salvatru_01",
			"g_m_m_salvatru_02",
			"g_m_m_salvaboss_01",
			"g_m_m_strpunk_01",
			"g_m_m_strpunk_02",
			// Gang Male Young
			"g_m_y_armygoon_01",
			"g_m_y_armygoon_02",
			"g_m_y_azteca_01",
			"g_m_y_azteca_02",
			"g_m_y_ballasog",
			"g_m_y_ballas_01",
			"g_m_y_ballas_02",
			"g_m_y_ballas_03",
			"g_m_y_bronfam_01",
			"g_m_y_bronfam_02",
			"g_m_y_chicels_01",
			"g_m_y_chicels_02",
			"g_m_y_chinese_01",
			"g_m_y_chinese_02",
			"g_m_y_deadsk8_01",
			"g_m_y_deadsk8_02",
			"g_m_y_famdnf_01",
			"g_m_y_famfor_01",
			"g_m_y_famfor_02",
			"g_m_y_korean_01",
			"g_m_y_korean_02",
			"g_m_y_lost_01",
			"g_m_y_lost_02",
			"g_m_y_lost_03",
			"g_m_y_mexgang_01",
			"g_m_y_mexgang_02",
			"g_m_y_mexthug_01",
			"g_m_y_prisgoon_01",
			"g_m_y_prisgoon_02",
			"g_m_y_prisgoon_03",
			"g_m_y_prologb_01",
			"g_m_y_prologb_02",
			"g_m_y_salvaboss_01",
			"g_m_y_salvaboss_02",
			"g_m_y_salvagoon_01",
			"g_m_y_salvagoon_02",
			"g_m_y_salvagoon_03",
			"g_m_y_vagos_01",
			"g_m_y_vagos_02",
			// Gang Female
			"g_f_y_ballas_01",
			"g_f_y_families_01",
			"g_f_y_lost_01",
			// Service Male Middle-Age
			"s_m_m_amuboss_01",
			"s_m_m_carwash_01",
			"s_m_m_chemsec_01",
			"s_m_m_cntrybar_01",
			"s_m_m_dockwork_01",
			"s_m_m_dockwork_02",
			"s_m_m_doctor_01",
			"s_m_m_fiboffice_01",
			"s_m_m_fiboffice_02",
			"s_m_m_financier_01",
			"s_m_m_garbage",
			"s_m_m_gentransport",
			"s_m_m_hairdress_01",
			"s_m_m_highsec_01",
			"s_m_m_highsec_02",
			"s_m_m_janitor",
			"s_m_m_lathandy_01",
			"s_m_m_lifeinvad_01",
			"s_m_m_linecook",
			"s_m_m_lsmetro_01",
			"s_m_m_mariachi_01",
			"s_m_m_migrant_01",
			"s_m_m_migrant_02",
			"s_m_m_movprem_01",
			"s_m_m_paramedic_01",
			"s_m_m_pilot_01",
			"s_m_m_pilot_02",
			"s_m_m_postal_01",
			"s_m_m_postal_02",
			"s_m_m_prisguard_01",
			"s_m_m_promourn_01",
			"s_m_m_repairman_01",
			"s_m_m_retailstaff",
			"s_m_m_scientist_01",
			"s_m_m_security_01",
			"s_m_m_strgrsec_01",
			"s_m_m_strgrsec_02",
			"s_m_m_strvend_01",
			"s_m_m_strvend_02",
			"s_m_m_swat_01",
			"s_m_m_trucker_01",
			"s_m_m_ups_01",
			"s_m_m_ups_02",
			"s_m_m_valet_01",
			"s_m_m_waiter_01",
			// Service Male Old
			"s_m_o_busker_01",
			// Service Male Young
			"s_m_y_airworker_01",
			"s_m_y_airworker_02",
			"s_m_y_ammucity_01",
			"s_m_y_ammucity_02",
			"s_m_y_armymech_01",
			"s_m_y_baywatch_01",
			"s_m_y_blackops_01",
			"s_m_y_blackops_02",
			"s_m_y_blackops_03",
			"s_m_y_busboy_01",
			"s_m_y_chef_01",
			"s_m_y_chef_02",
			"s_m_y_clown_01",
			"s_m_y_construct_01",
			"s_m_y_construct_02",
			"s_m_y_cop_01",
			"s_m_y_correctional_01",
			"s_m_y_correctional_02",
			"s_m_y_cyclist_01",
			"s_m_y_dealer_01",
			"s_m_y_devinsec_01",
			"s_m_y_dockwork_01",
			"s_m_y_doorman_01",
			"s_m_y_dwservice_01",
			"s_m_y_dwservice_02",
			"s_m_y_factory_01",
			"s_m_y_fireman_01",
			"s_m_y_garbage",
			"s_m_y_gardener_01",
			"s_m_y_hazmat_01",
			"s_m_y_hwaycop_01",
			"s_m_y_lifeinvad_01",
			"s_m_y_lsmetro_01",
			"s_m_y_maint_01",
			"s_m_y_marine_01",
			"s_m_y_marine_02",
			"s_m_y_marine_03",
			"s_m_y_migrant_01",
			"s_m_y_paparazzi_01",
			"s_m_y_pilot_01",
			"s_m_y_pilot_02",
			"s_m_y_pilot_03",
			"s_m_y_prolog_01",
			"s_m_y_prolog_02",
			"s_m_y_ranger_01",
			"s_m_y_ranger_02",
			"s_m_y_robber_01",
			"s_m_y_security_01",
			"s_m_y_sheriff_01",
			"s_m_y_sheriff_02",
			"s_m_y_shop_mask_01",
			"s_m_y_strvalets_01",
			"s_m_y_strvalets_02",
			"s_m_y_swat_01",
			"s_m_y_trucker_01",
			"s_m_y_uscg_01",
			"s_m_y_valet_01",
			"s_m_y_waiter_01",
			"s_m_y_winclean_01",
			// Service Female
			"s_f_m_fembarend_01",
			"s_f_m_maid_01",
			"s_f_m_shop_high",
			"s_f_y_airhostess_01",
			"s_f_y_airhostess_02",
			"s_f_y_beach_01",
			"s_f_y_busker_01",
			"s_f_y_cop_01",
			"s_f_y_dancer_01",
			"s_f_y_factory_01",
			"s_f_y_femoffice_01",
			"s_f_y_hooker_01",
			"s_f_y_hooker_02",
			"s_f_y_lifeinvad_01",
			"s_f_y_pilot_01",
			"s_f_y_scrubs_01",
			"s_f_y_sheriff_01",
			"s_f_y_shop_high_01",
			"s_f_y_shop_low_01",
			"s_f_y_shop_low_02",
			"s_f_y_shop_mid_01",
			"s_f_y_spa_01",
			"s_f_y_stripper_01",
			"s_f_y_stripper_02",
			"s_f_y_stripperlite_01",
			"s_f_y_valet_01",
			"s_f_y_winclean_01",
			// Story Characters (cs_)
			"cs_amandatownley",
			"cs_andreas",
			"cs_ashley",
			"cs_bankman",
			"cs_barry",
			"cs_beverly",
			"cs_brad",
			"cs_bradcadaver",
			"cs_carbuyer",
			"cs_casey",
			"cs_chef",
			"cs_chengsr",
			"cs_chrisformage",
			"cs_clay",
			"cs_dale",
			"cs_davenorton",
			"cs_debra",
			"cs_denise",
			"cs_devin",
			"cs_dom",
			"cs_dreyfuss",
			"cs_drfriedlander",
			"cs_fabien",
			"cs_fbisuit_01",
			"cs_floyd",
			"cs_guadalope",
			"cs_gurk",
			"cs_hunter",
			"cs_janet",
			"cs_jewelass",
			"cs_jimmyboston",
			"cs_jimmydisanto",
			"cs_joeminuteman",
			"cs_josef",
			"cs_josh",
			"cs_karen_daniels",
			"cs_lamardavis",
			"cs_lazlow",
			"cs_lestercrest",
			"cs_lifeinvad_01",
			"cs_magenta",
			"cs_manuel",
			"cs_marnie",
			"cs_maryann",
			"cs_maude",
			"cs_michelle",
			"cs_milton",
			"cs_molly",
			"cs_moviestar",
			"cs_mrgk",
			"cs_nervousron",
			"cs_nigel",
			"cs_old_man1a",
			"cs_old_man2",
			"cs_omega",
			"cs_orleans",
			"cs_ortega",
			"cs_paper",
			"cs_patricia",
			"cs_priest",
			"cs_prolsec_01",
			"cs_prolsec_02",
			"cs_ramp_gang",
			"cs_ramp_hic",
			"cs_ramp_hipster",
			"cs_ramp_marine",
			"cs_ramp_mex",
			"cs_reporter",
			"cs_roccopelosi",
			"cs_russiandrunk",
			"cs_siemonyetarian",
			"cs_solomon",
			"cs_stevehains",
			"cs_stretch",
			"cs_tanisha",
			"cs_taocheng",
			"cs_taostranslator",
			"cs_tenniscoach",
			"cs_terry",
			"cs_tomepsilon",
			"cs_tonya",
			"cs_tracydisanto",
			"cs_trevorstephens",
			"cs_wade",
			"cs_zimbor",
			// Multiplayer Models (mp_)
			"mp_m_avongoon",
			"mp_m_bogdangoon",
			"mp_m_doorman",
			"mp_m_exarmy_01",
			"mp_m_gore",
			"mp_m_grabber_01",
			"mp_m_headmus",
			"mp_m_hijacker",
			"mp_m_hostage_01",
			"mp_m_lazlow_01",
			"mp_m_migrant_01",
			"mp_m_paramedic_01",
			"mp_m_prisonguard",
			"mp_m_prosec_01",
			"mp_m_prison_01",
			"mp_m_repairman_01",
			"mp_m_shopkeep_01",
			"mp_m_waremech_01",
			"mp_f_execpa_01",
			"mp_f_execpa_02",
			"mp_f_misty_01",
			// Unique Male Middle-Age (u_m_m_)
			"u_m_m_aldinapoli",
			"u_m_m_bankman",
			"u_m_m_baygor",
			"u_m_m_bullperson",
			"u_m_m_canebros",
			"u_m_m_chef",
			"u_m_m_corpse_01",
			"u_m_m_corpse_02",
			"u_m_m_crogoon_01",
			"u_m_m_doa_01",
			"u_m_m_edtoh",
			"u_m_m_fibarchvist",
			"u_m_m_filmdirector",
			"u_m_m_goon_01",
			"u_m_m_guido_01",
			"u_m_m_hargoon_01",
			"u_m_m_jewelsec_01",
			"u_m_m_juggernaut",
			"u_m_m_lost_01",
			"u_m_m_mani",
			"u_m_m_mccmill",
			"u_m_m_mclough",
			"u_m_m_mkboss",
			"u_m_m_mrdk",
			"u_m_m_proldriver",
			"u_m_m_promourn_01",
			"u_m_m_rashcosvki",
			"u_m_m_reaper",
			"u_m_m_rivalpap",
			"u_m_m_rogues_01",
			"u_m_m_scafgoon_01",
			"u_m_m_taphillbilly",
			"u_m_m_tattoo_01",
			"u_m_m_tramp_01",
			"u_m_m_tugsec_01",
			"u_m_m_vince",
			"u_m_m_vinewood01_01",
			"u_m_m_vinewood01_02",
			"u_m_m_vinewood01_03",
			"u_m_m_vinewood01_04",
			// Unique Male Old (u_m_o_)
			"u_m_o_finguru_01",
			"u_m_o_soucent_01",
			"u_m_o_yacht_01",
			// Unique Male Young (u_m_y_)
			"u_m_y_abner",
			"u_m_y_antonb",
			"u_m_y_avery_01",
			"u_m_y_babyd_01",
			"u_m_y_baygor",
			"u_m_y_beastie",
			"u_m_y_burgerdrug_01",
			"u_m_y_chip",
			"u_m_y_cyclist_01",
			"u_m_y_daveywilliams",
			"u_m_y_devingoon_01",
			"u_m_y_drug_01",
			"u_m_y_executor_01",
			"u_m_y_frontsec_01",
			"u_m_y_frontsec_02",
			"u_m_y_goon_01",
			"u_m_y_guido_01",
			"u_m_y_hairdress_01",
			"u_m_y_humpig",
			"u_m_y_juggernaut",
			"u_m_y_jetski_01",
			"u_m_y_lostmcburnt",
			"u_m_y_mani",
			"u_m_y_methlab_01",
			"u_m_y_methlab_02",
			"u_m_y_movactor_01",
			"u_m_y_pogo_01",
			"u_m_y_prisoner_01",
			"u_m_y_proldriver_01",
			"u_m_y_prolhost_01",
			"u_m_y_robber_01",
			"u_m_y_rsranger_01",
			"u_m_y_sbike",
			"u_m_y_soucent_01",
			"u_m_y_soucent_02",
			"u_m_y_stbla_01",
			"u_m_y_stbla_02",
			"u_m_y_tattooed_01",
			"u_m_y_td_01",
			"u_m_y_trailerpark_01",
			"u_m_y_tranvest_01",
			"u_m_y_videoteam_01",
			"u_m_y_wigger_01",
			// Unique Female
			"u_f_m_corpse_01",
			"u_f_m_geisha_01",
			"u_f_m_miranda",
			"u_f_m_promourn_01",
			"u_f_o_memgirl",
			"u_f_y_bikerchic",
			"u_f_y_comjane",
			"u_f_y_coroner_01",
			"u_f_y_femgoon_01",
			"u_f_y_frontsec_01",
			"u_f_y_goon_01",
			"u_f_y_hooker_01",
			"u_f_y_mistress",
			"u_f_y_moviestar_01",
			"u_f_y_poppymich",
			"u_f_y_prolhost_01",
			"u_f_y_reporter_01",
			"u_f_y_seclub_01",
		};
	}

	CommandTabTransformPlayable::CommandTabTransformPlayable(CommandList* parent)
		: CommandList(parent, LIT("Playable Characters"))
	{
		for (const auto& e : kPlayable)
			createChild<CommandTransformModel>(LIT(e.label), Joaat(e.model));
	}

	CommandTabTransformGroundAnimals::CommandTabTransformGroundAnimals(CommandList* parent)
		: CommandList(parent, LIT("Ground Animals"))
	{
		for (const auto& e : kGroundAnimals)
			createChild<CommandTransformModel>(LIT(e.label), Joaat(e.model));
	}

	CommandTabTransformWaterAnimals::CommandTabTransformWaterAnimals(CommandList* parent)
		: CommandList(parent, LIT("Water Animals"))
	{
		for (const auto& e : kWaterAnimals)
			createChild<CommandTransformModel>(LIT(e.label), Joaat(e.model));
	}

	CommandTabTransformFlyingAnimals::CommandTabTransformFlyingAnimals(CommandList* parent)
		: CommandList(parent, LIT("Flying Animals"))
	{
		for (const auto& e : kFlyingAnimals)
			createChild<CommandTransformModel>(LIT(e.label), Joaat(e.model));
	}

	CommandTabTransformNPCs::CommandTabTransformNPCs(CommandList* parent)
		: CommandList(parent, LIT("NPCs"))
	{
		for (const char* model : kNPCModels)
			createChild<CommandTransformModel>(LIT(model), Joaat(model));
	}

	void CommandFindModel::onCommand(Click& click, std::wstring& args)
	{
		if (args.empty())
		{
			LOGF(INFO, "[findmodel] Usage: findmodel <clue>");
			return;
		}

		const std::string clue(args.begin(), args.end());

		int found = 0;

		auto search = [&](const CommandList* list)
		{
			for (const auto& child : list->children)
			{
				const std::string& name = child->getPhysical()->menu_name.literal_str;
				if (name.find(clue) != std::string::npos)
				{
					LOGF(INFO, "[findmodel] {}", name);
					++found;
				}
			}
		};

		search(m_npcs);

		if (found == 0)
			LOGF(INFO, "[findmodel] No models matching '{}'", clue);
		else
			LOGF(INFO, "[findmodel] {} result(s)", found);
	}
}

namespace Stand::Features
{
	Stand::CommandTabTransform& GetCommandTabTransform()
	{
		static Stand::CommandTabTransform instance{};
		return instance;
	}
}
