#include "Vehicle/VehicleData.hpp"

const VehicleEntry g_VehicleData[] = {
    { "adder", "Game Launch" },
    { "airbus", "Game Launch" },
    { "airtug", "Game Launch" },
    { "akula", "The Doomsday Heist" },
    { "akuma", "Game Launch" },
    { "aleutian", "The Chop Shop" },
    { "alkonost", "Cayo Perico Heist" },
    { "alpha", "Business" },
    { "alphaz1", "Smuggler's Run" },
    { "ambulance", "Game Launch" },
    { "annihilator", "Game Launch" },
    { "annihilator2", "Cayo Perico Heist" },
    { "apc", "Gunrunning Pack" },
    { "arbitergt", "The Criminal Enterprises" },
    { "ardent", "Gunrunning Pack" },
    { "armytanker", "Game Launch" },
    { "armytrailer", "Game Launch" },
    { "armytrailer2", "Game Launch" },
    { "asbo", "Diamond Casino Heist" },
    { "asea", "Game Launch" },
    { "asea2", "Game Launch" },
    { "asterope", "Game Launch" },
    { "asterope2", "The Chop Shop" },
    { "astrale", "A Safehouse in the Hills" },
    { "astron", "The Contract" },
    { "astron2", "Los Santos Drug Wars" },
    { "autarch", "The Doomsday Heist" },
    { "avarus", "Bikers" },
    { "avenger", "The Doomsday Heist" },
    { "avenger2", "The Doomsday Heist" },
    { "avenger3", "San Andreas Mercenaries" },
    { "avenger4", "San Andreas Mercenaries" },
    { "avisa", "Cayo Perico Heist" },
    { "bagger", "Game Launch" },
    { "baletrailer", "Game Launch" },
    { "baller", "Game Launch" },
    { "baller2", "Game Launch" },
    { "baller3", "Executives and Other Criminals" },
    { "baller4", "Executives and Other Criminals" },
    { "baller5", "Executives and Other Criminals" },
    { "baller6", "Executives and Other Criminals" },
    { "baller7", "The Contract" },
    { "baller8", "The Chop Shop" },
    { "banshee", "Game Launch" },
    { "banshee2", "January 2016" },
    { "banshee3", "Agents of Sabotage" },
    { "barracks", "Game Launch" },
    { "barracks2", "Game Launch" },
    { "barracks3", "Heists DLC" },
    { "barrage", "The Doomsday Heist" },
    { "bati", "Game Launch" },
    { "bati2", "Game Launch" },
    { "benson", "Game Launch" },
    { "benson2", "The Chop Shop" },
    { "besra", "SA Flight School" },
    { "bestiagts", "Further Adventures in Finance and Felony" },
    { "bf400", "Cunning Stunts" },
    { "bfinjection", "Game Launch" },
    { "biff", "Game Launch" },
    { "bifta", "Beach Bum" },
    { "bison", "Game Launch" },
    { "bison2", "Game Launch" },
    { "bison3", "Game Launch" },
    { "bjxl", "Game Launch" },
    { "blade", "I'm Not a Hipster" },
    { "blazer", "Game Launch" },
    { "blazer2", "Game Launch" },
    { "blazer3", "Game Launch" },
    { "blazer4", "Bikers" },
    { "blazer5", "Import/Export" },
    { "blimp", "Game Launch" },
    { "blimp2", "Next Gen Release" },
    { "blimp3", "After Hours" },
    { "blista", "Game Launch" },
    { "blista2", "Next Gen Release" },
    { "blista3", "Next Gen Release" },
    { "bmx", "Game Launch" },
    { "boattrailer", "Game Launch" },
    { "boattrailer2", "The Chop Shop" },
    { "boattrailer3", "The Chop Shop" },
    { "bobcatxl", "Game Launch" },
    { "bodhi2", "Game Launch" },
    { "bombushka", "Smuggler's Run" },
    { "boor", "Drug Wars" },
    { "boxville", "Game Launch" },
    { "boxville2", "Game Launch" },
    { "boxville3", "Game Launch" },
    { "boxville4", "Heists DLC" },
    { "boxville5", "Import/Export" },
    { "boxville6", "The Chop Shop" },
    { "brawler", "Ill-Gotten Gains Part 2" },
    { "brickade", "Further Adventures in Finance and Felony" },
    { "brickade2", "Drug Wars" },
    { "brigham", "San Andreas Mercenaries" },
    { "brioso", "Cunning Stunts" },
    { "brioso2", "Cayo Perico Heist" },
    { "brioso3", "The Criminal Enterprises" },
    { "broadway", "Drug Wars" },
    { "bruiser", "Arena War" },
    { "bruiser2", "Arena War" },
    { "bruiser3", "Arena War" },
    { "brutus", "Arena War" },
    { "brutus2", "Arena War" },
    { "brutus3", "Arena War" },
    { "btype", "Valentine's Day Massacre" },
    { "btype2", "Halloween Surprise" },
    { "btype3", "Be My Valentine" },
    { "buccaneer", "Game Launch" },
    { "buccaneer2", "Lowriders" },
    { "buffalo", "Game Launch" },
    { "buffalo2", "Game Launch" },
    { "buffalo3", "Next Gen Release" },
    { "buffalo4", "The Contract" },
    { "buffalo5", "San Andreas Mercenaries" },
    { "bulldozer", "Game Launch" },
    { "bullet", "Game Launch" },
    { "burrito", "Game Launch" },
    { "burrito2", "Game Launch" },
    { "burrito3", "Game Launch" },
    { "burrito4", "Game Launch" },
    { "burrito5", "Game Launch" },
    { "bus", "Game Launch" },
    { "buzzard", "Game Launch" },
    { "buzzard2", "Game Launch" },
    { "cablecar", "Game Launch" },
    { "caddy", "Game Launch" },
    { "caddy2", "Game Launch" },
    { "caddy3", "Gunrunning Pack" },
    { "calico", "LS Tuners" },
    { "camper", "Game Launch" },
    { "caracara", "Southern SA Super Sport Series" },
    { "caracara2", "Diamond Casino & Resort" },
    { "caracara3", "The Kortz Center Heist" },
    { "carbonizzare", "Game Launch" },
    { "carbonrs", "Game Launch" },
    { "cargobob", "Game Launch" },
    { "cargobob2", "Game Launch" },
    { "cargobob3", "Game Launch" },
    { "cargobob4", "Executives and Other Criminals" },
    { "cargobob5", "Agents of Sabotage" },
    { "cargoplane", "Game Launch" },
    { "cargoplane2", "Drug Wars" },
    { "cartuccia", "The Kortz Center Heist" },
    { "casco", "Heists DLC" },
    { "castigator", "Bottom Dollar Bounties" },
    { "cavalcade", "Game Launch" },
    { "cavalcade2", "Game Launch" },
    { "cavalcade3", "The Chop Shop" },
    { "cerberus", "Arena War" },
    { "cerberus2", "Arena War" },
    { "cerberus3", "Arena War" },
    { "champion", "The Contract" },
    { "chavosv6", "Agents of Sabotage" },
    { "cheburek", "Southern SA Super Sport Series" },
    { "cheetah", "Game Launch" },
    { "cheetah2", "Gunrunning Pack" },
    { "cheetah3", "Money Fronts" },
    { "chernobog", "The Doomsday Heist" },
    { "chimera", "Bikers" },
    { "chino", "Ill-Gotten Gains Part 2" },
    { "chino2", "Lowriders" },
    { "cinquemila", "The Contract" },
    { "cliffhanger", "Cunning Stunts" },
    { "clique", "Arena War" },
    { "clique2", "San Andreas Mercenaries" },
    { "club", "LS Summer Special" },
    { "coach", "Game Launch" },
    { "cog55", "Executives and Other Criminals" },
    { "cog552", "Executives and Other Criminals" },
    { "cogcabrio", "Game Launch" },
    { "cognoscenti", "Executives and Other Criminals" },
    { "cognoscenti2", "Executives and Other Criminals" },
    { "comet2", "Game Launch" },
    { "comet3", "Import/Export" },
    { "comet4", "The Doomsday Heist" },
    { "comet5", "The Doomsday Heist" },
    { "comet6", "LS Tuners" },
    { "comet7", "The Contract" },
    { "conada", "The Criminal Enterprises" },
    { "conada2", "San Andreas Mercenaries" },
    { "contender", "Cunning Stunts" },
    { "coquette", "Game Launch" },
    { "coquette2", "SA Flight School" },
    { "coquette3", "Ill-Gotten Gains Part 2" },
    { "coquette4", "LS Summer Special" },
    { "coquette5", "Bottom Dollar Bounties" },
    { "coquette6", "Agents of Sabotage" },
    { "corsita", "The Criminal Enterprises" },
    { "coureur", "San Andreas Mercenaries" },
    { "cruiser", "Game Launch" },
    { "crusader", "Game Launch" },
    { "cuban800", "Game Launch" },
    { "cutter", "Game Launch" },
    { "cyclone", "Smuggler's Run" },
    { "cyclone2", "The Contract" },
    { "cypher", "LS Tuners" },
    { "daemon", "Game Launch" },
    { "daemon2", "Bikers" },
    { "deathbike", "Arena War" },
    { "deathbike2", "Arena War" },
    { "deathbike3", "Arena War" },
    { "defiler", "Bikers" },
    { "deity", "The Contract" },
    { "deluxo", "The Doomsday Heist" },
    { "deveste", "Arena War" },
    { "deviant", "Arena War" },
    { "diablous", "Import/Export" },
    { "diablous2", "Import/Export" },
    { "dilettante", "Game Launch" },
    { "dilettante2", "Game Launch" },
    { "dinghy", "Game Launch" },
    { "dinghy2", "Game Launch" },
    { "dinghy3", "Heists DLC" },
    { "dinghy4", "Executives and Other Criminals" },
    { "dinghy5", "Cayo Perico Heist" },
    { "dloader", "Game Launch" },
    { "docktrailer", "Game Launch" },
    { "docktug", "Game Launch" },
    { "dodo", "Next Gen Release" },
    { "dominator", "Game Launch" },
    { "dominator10", "Bottom Dollar Bounties" },
    { "dominator2", "Next Gen Release" },
    { "dominator3", "Southern SA Super Sport Series" },
    { "dominator4", "Arena War" },
    { "dominator5", "Arena War" },
    { "dominator6", "Arena War" },
    { "dominator7", "LS Tuners" },
    { "dominator8", "LS Tuners" },
    { "dominator9", "The Chop Shop" },
    { "dorado", "The Chop Shop" },
    { "double", "Game Launch" },
    { "drafter", "Diamond Casino & Resort" },
    { "draugur", "The Criminal Enterprises" },
    { "driftchavosv6", "Money Fronts" },
    { "driftcheburek", "Agents of Sabotage" },
    { "driftcoquette", "The Kortz Center Heist" },
    { "driftcypher", "Bottom Dollar Bounties" },
    { "driftdominator10", "Money Fronts" },
    { "driftdominator8", "The Kortz Center Heist" },
    { "driftdominator9", "A Safehouse in the Hills" },
    { "driftelegy", "The Kortz Center Heist" },
    { "drifteuros", "The Chop Shop" },
    { "driftfr36", "The Chop Shop" },
    { "driftfuto", "The Chop Shop" },
    { "driftfuto2", "Agents of Sabotage" },
    { "driftgauntlet4", "Money Fronts" },
    { "drifthardy", "Money Fronts" },
    { "driftjester", "The Chop Shop" },
    { "driftjester3", "Agents of Sabotage" },
    { "driftkeitora", "A Safehouse in the Hills" },
    { "driftl352", "Money Fronts" },
    { "driftnebula", "Bottom Dollar Bounties" },
    { "driftremus", "The Chop Shop" },
    { "driftrt3000", "A Safehouse in the Hills" },
    { "driftsentinel", "Bottom Dollar Bounties" },
    { "driftsentinel2", "A Safehouse in the Hills" },
    { "drifttampa", "The Chop Shop" },
    { "driftvorschlag", "Bottom Dollar Bounties" },
    { "driftyosemite", "The Chop Shop" },
    { "driftzr350", "The Chop Shop" },
    { "dubsta", "Game Launch" },
    { "dubsta2", "Game Launch" },
    { "dubsta3", "I'm Not a Hipster" },
    { "dukes", "Next Gen Release" },
    { "dukes2", "Next Gen Release" },
    { "dukes3", "LS Summer Special" },
    { "dump", "Game Launch" },
    { "dune", "Game Launch" },
    { "dune2", "Game Launch" },
    { "dune3", "Gunrunning Pack" },
    { "dune4", "Import/Export" },
    { "dune5", "Import/Export" },
    { "duster", "Game Launch" },
    { "duster2", "Agents of Sabotage" },
    { "dynasty", "Diamond Casino & Resort" },
    { "elegy", "Import/Export" },
    { "elegy2", "Game Launch" },
    { "ellie", "Southern SA Super Sport Series" },
    { "emerus", "Diamond Casino & Resort" },
    { "emperor", "Game Launch" },
    { "emperor2", "Game Launch" },
    { "emperor3", "Game Launch" },
    { "enduro", "Heists DLC" },
    { "entity2", "Southern SA Super Sport Series" },
    { "entity3", "Drug Wars" },
    { "entityxf", "Game Launch" },
    { "envisage", "Bottom Dollar Bounties" },
    { "esskey", "Bikers" },
    { "estride", "The Kortz Center Heist" },
    { "eudora", "Drug Wars" },
    { "euros", "LS Tuners" },
    { "eurosx32", "Bottom Dollar Bounties" },
    { "everon", "Diamond Casino Heist" },
    { "everon2", "Drug Wars" },
    { "everon3", "Money Fronts" },
    { "exemplar", "Game Launch" },
    { "f620", "Game Launch" },
    { "faction", "Lowriders" },
    { "faction2", "Lowriders" },
    { "faction3", "Lowriders: Custom Classics" },
    { "fagaloa", "Southern SA Super Sport Series" },
    { "faggio", "Bikers" },
    { "faggio2", "Game Launch" },
    { "faggio3", "Bikers" },
    { "fbi", "Game Launch" },
    { "fbi2", "Game Launch" },
    { "fcr", "Import/Export" },
    { "fcr2", "Import/Export" },
    { "felon", "Game Launch" },
    { "felon2", "Game Launch" },
    { "feltzer2", "Game Launch" },
    { "feltzer3", "Ill-Gotten Gains Part 1" },
    { "firebolt", "Agents of Sabotage" },
    { "firetruk", "Game Launch" },
    { "fixter", "Game Launch" },
    { "flashgt", "Southern SA Super Sport Series" },
    { "flatbed", "Game Launch" },
    { "flatbed2", "Money Fronts" },
    { "fmj", "Further Adventures in Finance and Felony" },
    { "fmj2", "A Safehouse in the Hills" },
    { "forklift", "Game Launch" },
    { "formula", "Diamond Casino Heist" },
    { "formula2", "Diamond Casino Heist" },
    { "fq2", "Game Launch" },
    { "fr36", "The Chop Shop" },
    { "freecrawler", "After Hours" },
    { "freight", "Game Launch" },
    { "freight2", "The Chop Shop" },
    { "freightcar", "Game Launch" },
    { "freightcar2", "LS Tuners" },
    { "freightcar3", "Agents of Sabotage" },
    { "freightcont1", "Game Launch" },
    { "freightcont2", "Game Launch" },
    { "freightgrain", "Game Launch" },
    { "freighttrailer", "Game Launch" },
    { "frogger", "Game Launch" },
    { "frogger2", "Game Launch" },
    { "fugitive", "Game Launch" },
    { "furia", "Diamond Casino Heist" },
    { "furoregt", "Last Team Standing" },
    { "fusilade", "Game Launch" },
    { "futo", "Game Launch" },
    { "futo2", "LS Tuners" },
    { "gargoyle", "Cunning Stunts" },
    { "gauntlet", "Game Launch" },
    { "gauntlet2", "Next Gen Release" },
    { "gauntlet3", "Diamond Casino & Resort" },
    { "gauntlet4", "Diamond Casino & Resort" },
    { "gauntlet5", "LS Summer Special" },
    { "gauntlet6", "San Andreas Mercenaries" },
    { "gb200", "Southern SA Super Sport Series" },
    { "gburrito", "Game Launch" },
    { "gburrito2", "Heists DLC" },
    { "glendale", "I'm Not a Hipster" },
    { "glendale2", "LS Summer Special" },
    { "gp1", "Special Vehicle Circuit" },
    { "graintrailer", "Game Launch" },
    { "granger", "Game Launch" },
    { "granger2", "The Contract" },
    { "greenwood", "The Criminal Enterprises" },
    { "gresley", "Game Launch" },
    { "growler", "LS Tuners" },
    { "gt500", "The Doomsday Heist" },
    { "gt750", "A Safehouse in the Hills" },
    { "guardian", "Heists DLC" },
    { "habanero", "Game Launch" },
    { "hakuchou", "Last Team Standing" },
    { "hakuchou2", "Bikers" },
    { "halftrack", "Gunrunning Pack" },
    { "handler", "Game Launch" },
    { "hardy", "Money Fronts" },
    { "hauler", "Game Launch" },
    { "hauler2", "Gunrunning Pack" },
    { "havok", "Smuggler's Run" },
    { "hellion", "Diamond Casino & Resort" },
    { "hermes", "The Doomsday Heist" },
    { "hexer", "Game Launch" },
    { "horus", "The Kortz Center Heist" },
    { "hotknife", "Game Launch" },
    { "hotring", "Southern SA Super Sport Series" },
    { "howard", "Smuggler's Run" },
    { "hunter", "Smuggler's Run" },
    { "huntley", "High Life" },
    { "hustler", "The Doomsday Heist" },
    { "hydra", "Heists DLC" },
    { "ignus", "The Contract" },
    { "ignus2", "The Criminal Enterprises" },
    { "imorgon", "Diamond Casino Heist" },
    { "impaler", "Arena War" },
    { "impaler2", "Arena War" },
    { "impaler3", "Arena War" },
    { "impaler4", "Arena War" },
    { "impaler5", "The Chop Shop" },
    { "impaler6", "The Chop Shop" },
    { "imperator", "Arena War" },
    { "imperator2", "Arena War" },
    { "imperator3", "Arena War" },
    { "inductor", "San Andreas Mercenaries" },
    { "inductor2", "San Andreas Mercenaries" },
    { "infernus", "Game Launch" },
    { "infernus2", "Special Vehicle Circuit" },
    { "ingot", "Game Launch" },
    { "innovation", "Last Team Standing" },
    { "insurgent", "Heists DLC" },
    { "insurgent2", "Heists DLC" },
    { "insurgent3", "Gunrunning Pack" },
    { "intruder", "Game Launch" },
    { "issi2", "Game Launch" },
    { "issi3", "Southern SA Super Sport Series" },
    { "issi4", "Arena War" },
    { "issi5", "Arena War" },
    { "issi6", "Arena War" },
    { "issi7", "Diamond Casino & Resort" },
    { "issi8", "Drug Wars" },
    { "itali2", "A Safehouse in the Hills" },
    { "italigtb", "Import/Export" },
    { "italigtb2", "Import/Export" },
    { "italigto", "Arena War" },
    { "italirsx", "Cayo Perico Heist" },
    { "iwagen", "The Contract" },
    { "jackal", "Game Launch" },
    { "jb700", "Game Launch" },
    { "jb7002", "Diamond Casino Heist" },
    { "jester", "Business" },
    { "jester2", "Festive Surprise 2014" },
    { "jester3", "Southern SA Super Sport Series" },
    { "jester4", "LS Tuners" },
    { "jester5", "Agents of Sabotage" },
    { "jet", "Game Launch" },
    { "jetmax", "Game Launch" },
    { "journey", "Game Launch" },
    { "journey2", "Drug Wars" },
    { "jubilee", "The Contract" },
    { "jugular", "Diamond Casino & Resort" },
    { "kalahari", "Beach Bum" },
    { "kamacho", "The Doomsday Heist" },
    { "kanjo", "Diamond Casino Heist" },
    { "kanjosj", "The Criminal Enterprises" },
    { "keitora", "A Safehouse in the Hills" },
    { "khamelion", "Game Launch" },
    { "khanjali", "The Doomsday Heist" },
    { "komoda", "Diamond Casino Heist" },
    { "kosatka", "Cayo Perico Heist" },
    { "krieger", "Diamond Casino & Resort" },
    { "kuruma", "Heists DLC" },
    { "kuruma2", "Heists DLC" },
    { "l35", "San Andreas Mercenaries" },
    { "l352", "Money Fronts" },
    { "landstalker", "Game Launch" },
    { "landstalker2", "LS Summer Special" },
    { "laufer", "The Kortz Center Heist" },
    { "lazer", "Game Launch" },
    { "le7b", "Cunning Stunts" },
    { "lectro", "Heists DLC" },
    { "lguard", "Game Launch" },
    { "limo2", "Executives and Other Criminals" },
    { "lm87", "The Criminal Enterprises" },
    { "locust", "Diamond Casino & Resort" },
    { "longfin", "Cayo Perico Heist" },
    { "lrcgt", "The Kortz Center Heist" },
    { "luiva", "A Safehouse in the Hills" },
    { "lurcher", "Halloween Surprise" },
    { "luxor", "Game Launch" },
    { "luxor2", "Ill-Gotten Gains Part 1" },
    { "lynx", "Cunning Stunts" },
    { "mamba", "Executives and Other Criminals" },
    { "mammatus", "Game Launch" },
    { "manana", "Game Launch" },
    { "manana2", "LS Summer Special" },
    { "manchez", "Bikers" },
    { "manchez2", "Cayo Perico Heist" },
    { "manchez3", "Drug Wars" },
    { "marquis", "Game Launch" },
    { "marshall", "Next Gen Release" },
    { "massacro", "High Life" },
    { "massacro2", "Festive Surprise 2014" },
    { "maverick", "Game Launch" },
    { "maverick2", "Money Fronts" },
    { "menacer", "After Hours" },
    { "merula", "The Kortz Center Heist" },
    { "mesa", "Game Launch" },
    { "mesa2", "Game Launch" },
    { "mesa3", "Game Launch" },
    { "metrotrain", "Game Launch" },
    { "michelli", "Southern SA Super Sport Series" },
    { "microlight", "Smuggler's Run" },
    { "miljet", "SA Flight School" },
    { "minimus", "Money Fronts" },
    { "minitank", "Diamond Casino Heist" },
    { "minivan", "Game Launch" },
    { "minivan2", "Lowriders: Custom Classics" },
    { "mixer", "Game Launch" },
    { "mixer2", "Game Launch" },
    { "mogul", "Smuggler's Run" },
    { "molotok", "Smuggler's Run" },
    { "monroe", "Game Launch" },
    { "monster", "Independence Day" },
    { "monster3", "Arena War" },
    { "monster4", "Arena War" },
    { "monster5", "Arena War" },
    { "monstrociti", "San Andreas Mercenaries" },
    { "moonbeam", "Lowriders" },
    { "moonbeam2", "Lowriders" },
    { "mower", "Game Launch" },
    { "mule", "Game Launch" },
    { "mule2", "Game Launch" },
    { "mule3", "Heists DLC" },
    { "mule4", "After Hours" },
    { "mule5", "The Contract" },
    { "nebula", "Diamond Casino & Resort" },
    { "nemesis", "Game Launch" },
    { "neo", "Diamond Casino & Resort" },
    { "neon", "The Doomsday Heist" },
    { "nero", "Import/Export" },
    { "nero2", "Import/Export" },
    { "nightblade", "Bikers" },
    { "nightshade", "Executives and Other Criminals" },
    { "nightshark", "Gunrunning Pack" },
    { "nimbus", "Further Adventures in Finance and Felony" },
    { "ninef", "Game Launch" },
    { "ninef2", "Game Launch" },
    { "niobe", "Bottom Dollar Bounties" },
    { "nokota", "Smuggler's Run" },
    { "novak", "Diamond Casino & Resort" },
    { "omnis", "Cunning Stunts" },
    { "omnisegt", "The Criminal Enterprises" },
    { "openwheel1", "LS Summer Special" },
    { "openwheel2", "LS Summer Special" },
    { "oppressor", "Gunrunning Pack" },
    { "oppressor2", "After Hours" },
    { "oracle", "Game Launch" },
    { "oracle2", "Game Launch" },
    { "osiris", "Ill-Gotten Gains Part 1" },
    { "outlaw", "Diamond Casino Heist" },
    { "packer", "Game Launch" },
    { "panthere", "Drug Wars" },
    { "panto", "I'm Not a Hipster" },
    { "paradise", "Beach Bum" },
    { "paragon", "Diamond Casino & Resort" },
    { "paragon2", "Diamond Casino & Resort" },
    { "paragon3", "Bottom Dollar Bounties" },
    { "pariah", "The Doomsday Heist" },
    { "patriot", "Game Launch" },
    { "patriot2", "After Hours" },
    { "patriot3", "The Contract" },
    { "patrolboat", "Cayo Perico Heist" },
    { "pbus", "Game Launch" },
    { "pbus2", "After Hours" },
    { "pcj", "Game Launch" },
    { "penetrator", "Import/Export" },
    { "penumbra", "Game Launch" },
    { "penumbra2", "LS Summer Special" },
    { "peyote", "Game Launch" },
    { "peyote2", "Diamond Casino & Resort" },
    { "peyote3", "LS Summer Special" },
    { "pfister811", "Further Adventures in Finance and Felony" },
    { "phantom", "Game Launch" },
    { "phantom2", "Import/Export" },
    { "phantom3", "Gunrunning Pack" },
    { "phantom4", "The Chop Shop" },
    { "phoenix", "Game Launch" },
    { "picador", "Game Launch" },
    { "pigalle", "I'm Not a Hipster" },
    { "pipistrello", "Bottom Dollar Bounties" },
    { "pizzaboy", "Bottom Dollar Bounties" },
    { "polbuffalo", "A Safehouse in the Hills" },
    { "polbuffalo6", "A Safehouse in the Hills" },
    { "polcaracara", "Agents of Sabotage" },
    { "polcoquette4", "Agents of Sabotage" },
    { "poldominator10", "Bottom Dollar Bounties" },
    { "poldorado", "Bottom Dollar Bounties" },
    { "polfaction2", "Agents of Sabotage" },
    { "polgauntlet", "The Chop Shop" },
    { "polgreenwood", "Bottom Dollar Bounties" },
    { "police", "Game Launch" },
    { "police2", "Game Launch" },
    { "police3", "Game Launch" },
    { "police4", "Game Launch" },
    { "police5", "The Chop Shop" },
    { "policeb", "Game Launch" },
    { "policeb2", "Money Fronts" },
    { "policeold1", "Game Launch" },
    { "policeold2", "Game Launch" },
    { "policet", "Game Launch" },
    { "policet3", "Bottom Dollar Bounties" },
    { "polignus", "The Kortz Center Heist" },
    { "polimpaler5", "Bottom Dollar Bounties" },
    { "polimpaler6", "Bottom Dollar Bounties" },
    { "polmav", "Game Launch" },
    { "polterminus", "Agents of Sabotage" },
    { "pony", "Game Launch" },
    { "pony2", "Game Launch" },
    { "postlude", "The Criminal Enterprises" },
    { "pounder", "Game Launch" },
    { "pounder2", "After Hours" },
    { "powersurge", "Drug Wars" },
    { "prairie", "Game Launch" },
    { "pranger", "Game Launch" },
    { "predator", "Game Launch" },
    { "premier", "Game Launch" },
    { "previon", "LS Tuners" },
    { "primo", "Game Launch" },
    { "primo2", "Lowriders" },
    { "proptrailer", "Game Launch" },
    { "prototipo", "Further Adventures in Finance and Felony" },
    { "pyro", "Smuggler's Run" },
    { "r300", "Drug Wars" },
    { "radi", "Game Launch" },
    { "raiden", "The Doomsday Heist" },
    { "raiju", "San Andreas Mercenaries" },
    { "raketrailer", "Game Launch" },
    { "rallytruck", "Cunning Stunts" },
    { "rancherxl", "Game Launch" },
    { "rancherxl2", "Game Launch" },
    { "rapidgt", "Game Launch" },
    { "rapidgt2", "Game Launch" },
    { "rapidgt3", "Smuggler's Run" },
    { "rapidgt4", "Money Fronts" },
    { "raptor", "Bikers" },
    { "ratbike", "Bikers" },
    { "ratel", "San Andreas Mercenaries" },
    { "ratloader", "Game Launch" },
    { "ratloader2", "Festive Surprise 2014" },
    { "rcbandito", "Arena War" },
    { "reaper", "Further Adventures in Finance and Felony" },
    { "rebel", "Game Launch" },
    { "rebel2", "Game Launch" },
    { "rebla", "Diamond Casino Heist" },
    { "reever", "The Contract" },
    { "regina", "Game Launch" },
    { "remus", "LS Tuners" },
    { "rentalbus", "Game Launch" },
    { "retinue", "Smuggler's Run" },
    { "retinue2", "Diamond Casino Heist" },
    { "revolter", "The Doomsday Heist" },
    { "rhapsody", "I'm Not a Hipster" },
    { "rhinehart", "The Criminal Enterprises" },
    { "rhino", "Game Launch" },
    { "riata", "The Doomsday Heist" },
    { "riot", "Game Launch" },
    { "riot2", "The Doomsday Heist" },
    { "ripley", "Game Launch" },
    { "rocoto", "Game Launch" },
    { "rogue", "Smuggler's Run" },
    { "romero", "Game Launch" },
    { "rrocket", "Diamond Casino & Resort" },
    { "rt3000", "LS Tuners" },
    { "rubble", "Game Launch" },
    { "ruffian", "Game Launch" },
    { "ruiner", "Game Launch" },
    { "ruiner2", "Import/Export" },
    { "ruiner3", "Import/Export" },
    { "ruiner4", "The Criminal Enterprises" },
    { "rumpo", "Game Launch" },
    { "rumpo2", "Game Launch" },
    { "rumpo3", "Further Adventures in Finance and Felony" },
    { "ruston", "Special Vehicle Circuit" },
    { "s80", "Diamond Casino & Resort" },
    { "s95", "The Criminal Enterprises" },
    { "sabregt", "Game Launch" },
    { "sabregt2", "Lowriders: Custom Classics" },
    { "sadler", "Game Launch" },
    { "sadler2", "Game Launch" },
    { "sanchez", "Game Launch" },
    { "sanchez2", "Game Launch" },
    { "sanctus", "Bikers" },
    { "sandking", "Game Launch" },
    { "sandking2", "Game Launch" },
    { "savage", "Heists DLC" },
    { "savestra", "The Doomsday Heist" },
    { "sc1", "The Doomsday Heist" },
    { "scarab", "Arena War" },
    { "scarab2", "Arena War" },
    { "scarab3", "Arena War" },
    { "schafter2", "Game Launch" },
    { "schafter3", "Executives and Other Criminals" },
    { "schafter4", "Executives and Other Criminals" },
    { "schafter5", "Executives and Other Criminals" },
    { "schafter6", "Executives and Other Criminals" },
    { "schlagen", "Arena War" },
    { "schwarzer", "Game Launch" },
    { "scorcher", "Game Launch" },
    { "scramjet", "After Hours" },
    { "scrap", "Game Launch" },
    { "seabreeze", "Smuggler's Run" },
    { "seashark", "Game Launch" },
    { "seashark2", "Game Launch" },
    { "seashark3", "Executives and Other Criminals" },
    { "seasparrow", "Southern SA Super Sport Series" },
    { "seasparrow2", "Cayo Perico Heist" },
    { "seasparrow3", "Cayo Perico Heist" },
    { "seminole", "Game Launch" },
    { "seminole2", "LS Summer Special" },
    { "sentinel", "Game Launch" },
    { "sentinel2", "Game Launch" },
    { "sentinel3", "The Doomsday Heist" },
    { "sentinel4", "The Criminal Enterprises" },
    { "sentinel5", "Money Fronts" },
    { "sentinel6", "A Safehouse in the Hills" },
    { "serrano", "Game Launch" },
    { "seven70", "Further Adventures in Finance and Felony" },
    { "shamal", "Game Launch" },
    { "sheava", "Cunning Stunts" },
    { "sheriff", "Game Launch" },
    { "sheriff2", "Game Launch" },
    { "shinobi", "The Contract" },
    { "shotaro", "Bikers" },
    { "skylift", "Game Launch" },
    { "slamtruck", "Cayo Perico Heist" },
    { "slamvan", "Festive Surprise 2014" },
    { "slamvan2", "Heists DLC" },
    { "slamvan3", "Lowriders: Custom Classics" },
    { "slamvan4", "Arena War" },
    { "slamvan5", "Arena War" },
    { "slamvan6", "Arena War" },
    { "sm722", "The Criminal Enterprises" },
    { "sovereign", "Independence Day" },
    { "specter", "Import/Export" },
    { "specter2", "Import/Export" },
    { "speeder", "Beach Bum" },
    { "speeder2", "Executives and Other Criminals" },
    { "speedo", "Game Launch" },
    { "speedo2", "Game Launch" },
    { "speedo4", "After Hours" },
    { "speedo5", "San Andreas Mercenaries" },
    { "squaddie", "Cayo Perico Heist" },
    { "squalo", "Game Launch" },
    { "stafford", "After Hours" },
    { "stalion", "Next Gen Release" },
    { "stalion2", "Next Gen Release" },
    { "stanier", "Game Launch" },
    { "starling", "Smuggler's Run" },
    { "stinger", "Game Launch" },
    { "stingergt", "Game Launch" },
    { "stingertt", "San Andreas Mercenaries" },
    { "stockade", "Game Launch" },
    { "stockade3", "Game Launch" },
    { "stockade4", "Money Fronts" },
    { "stratum", "Game Launch" },
    { "streamer216", "San Andreas Mercenaries" },
    { "streiter", "The Doomsday Heist" },
    { "stretch", "Game Launch" },
    { "strikeforce", "After Hours" },
    { "stromberg", "The Doomsday Heist" },
    { "stryder", "Diamond Casino Heist" },
    { "stunt", "Game Launch" },
    { "submersible", "Game Launch" },
    { "submersible2", "Next Gen Release" },
    { "sugoi", "Diamond Casino Heist" },
    { "sultan", "Game Launch" },
    { "sultan2", "Diamond Casino Heist" },
    { "sultan3", "LS Tuners" },
    { "sultanrs", "January 2016" },
    { "suntrap", "Game Launch" },
    { "superd", "Game Launch" },
    { "supervolito", "Executives and Other Criminals" },
    { "supervolito2", "Executives and Other Criminals" },
    { "surano", "Game Launch" },
    { "surfer", "Game Launch" },
    { "surfer2", "Game Launch" },
    { "surfer3", "Drug Wars" },
    { "surge", "Game Launch" },
    { "suzume", "Money Fronts" },
    { "swift", "SA Flight School" },
    { "swift2", "Ill-Gotten Gains Part 1" },
    { "swinger", "After Hours" },
    { "t20", "Ill-Gotten Gains Part 2" },
    { "taco", "Game Launch" },
    { "tahoma", "Drug Wars" },
    { "tailgater", "Game Launch" },
    { "tailgater2", "LS Tuners" },
    { "taipan", "Southern SA Super Sport Series" },
    { "tampa", "Festive Surprise 2015" },
    { "tampa2", "Cunning Stunts" },
    { "tampa3", "Gunrunning Pack" },
    { "tampa4", "Money Fronts" },
    { "tanker", "Game Launch" },
    { "tanker2", "Heists DLC" },
    { "tankercar", "Game Launch" },
    { "taxi", "Game Launch" },
    { "technical", "Heists DLC" },
    { "technical2", "Import/Export" },
    { "technical3", "Gunrunning Pack" },
    { "tempesta", "Import/Export" },
    { "tenf", "The Criminal Enterprises" },
    { "tenf2", "The Criminal Enterprises" },
    { "terbyte", "After Hours" },
    { "terminus", "The Chop Shop" },
    { "tezeract", "Southern SA Super Sport Series" },
    { "thrax", "Diamond Casino & Resort" },
    { "thrust", "High Life" },
    { "thruster", "The Doomsday Heist" },
    { "tigon", "LS Summer Special" },
    { "tiptruck", "Game Launch" },
    { "tiptruck2", "Game Launch" },
    { "titan", "Game Launch" },
    { "titan2", "Agents of Sabotage" },
    { "toreador", "Cayo Perico Heist" },
    { "torero", "Gunrunning Pack" },
    { "torero2", "The Criminal Enterprises" },
    { "tornado", "Game Launch" },
    { "tornado2", "Game Launch" },
    { "tornado3", "Game Launch" },
    { "tornado4", "Game Launch" },
    { "tornado5", "Lowriders: Custom Classics" },
    { "tornado6", "Bikers" },
    { "toro", "Ill-Gotten Gains Part 2" },
    { "toro2", "Executives and Other Criminals" },
    { "toros", "Arena War" },
    { "tourbus", "Game Launch" },
    { "towtruck", "Game Launch" },
    { "towtruck2", "Game Launch" },
    { "towtruck3", "The Chop Shop" },
    { "towtruck4", "The Chop Shop" },
    { "tr2", "Game Launch" },
    { "tr3", "Game Launch" },
    { "tr4", "Game Launch" },
    { "tractor", "Game Launch" },
    { "tractor2", "Game Launch" },
    { "tractor3", "Game Launch" },
    { "trailerlarge", "Gunrunning Pack" },
    { "trailerlogs", "Game Launch" },
    { "trailers", "Game Launch" },
    { "trailers2", "Game Launch" },
    { "trailers3", "Game Launch" },
    { "trailers4", "Gunrunning Pack" },
    { "trailers5", "The Chop Shop" },
    { "trailersmall", "Game Launch" },
    { "trailersmall2", "Gunrunning Pack" },
    { "trash", "Game Launch" },
    { "trash2", "Heists DLC" },
    { "trflat", "Game Launch" },
    { "trflat2", "The Kortz Center Heist" },
    { "tribike", "Game Launch" },
    { "tribike2", "Game Launch" },
    { "tribike3", "Game Launch" },
    { "trophytruck", "Cunning Stunts" },
    { "trophytruck2", "Cunning Stunts" },
    { "tropic", "Game Launch" },
    { "tropic2", "Executives and Other Criminals" },
    { "tropos", "Cunning Stunts" },
    { "tug", "Further Adventures in Finance and Felony" },
    { "tula", "Smuggler's Run" },
    { "tulip", "Arena War" },
    { "tulip2", "Drug Wars" },
    { "turismo2", "Special Vehicle Circuit" },
    { "turismo3", "The Chop Shop" },
    { "turismor", "Business" },
    { "tvtrailer", "Game Launch" },
    { "tvtrailer2", "The Chop Shop" },
    { "tyrant", "Southern SA Super Sport Series" },
    { "tyrus", "Cunning Stunts" },
    { "uranus", "Agents of Sabotage" },
    { "utillitruck", "Game Launch" },
    { "utillitruck2", "Game Launch" },
    { "utillitruck3", "Game Launch" },
    { "vacca", "Game Launch" },
    { "vader", "Game Launch" },
    { "vagner", "Gunrunning Pack" },
    { "vagrant", "Diamond Casino Heist" },
    { "valkyrie", "Heists DLC" },
    { "valkyrie2", "Executives and Other Criminals" },
    { "vamos", "Arena War" },
    { "vectre", "LS Tuners" },
    { "velenogt", "The Kortz Center Heist" },
    { "velum", "Game Launch" },
    { "velum2", "Heists DLC" },
    { "verlierer2", "Executives and Other Criminals" },
    { "verus", "Cayo Perico Heist" },
    { "vestra", "Business" },
    { "vetir", "Cayo Perico Heist" },
    { "veto", "Cayo Perico Heist" },
    { "veto2", "Cayo Perico Heist" },
    { "vigero", "Game Launch" },
    { "vigero2", "The Criminal Enterprises" },
    { "vigero3", "The Chop Shop" },
    { "vigilante", "Smuggler's Run" },
    { "vindicator", "Ill-Gotten Gains Part 2" },
    { "virgo", "Ill-Gotten Gains Part 1" },
    { "virgo2", "Lowriders: Custom Classics" },
    { "virgo3", "Lowriders: Custom Classics" },
    { "virtue", "Drug Wars" },
    { "viseris", "The Doomsday Heist" },
    { "visione", "Smuggler's Run" },
    { "vivanite", "The Chop Shop" },
    { "vivanite2", "A Safehouse in the Hills" },
    { "volatol", "The Doomsday Heist" },
    { "volatus", "Further Adventures in Finance and Felony" },
    { "voltic", "Game Launch" },
    { "voltic2", "Import/Export" },
    { "voodoo", "Lowriders" },
    { "voodoo2", "Game Launch" },
    { "vorschlaghammer", "Bottom Dollar Bounties" },
    { "vortex", "Bikers" },
    { "vstr", "Diamond Casino Heist" },
    { "warden", "The Kortz Center Heist" },
    { "warrener", "I'm Not a Hipster" },
    { "warrener2", "LS Tuners" },
    { "washington", "Game Launch" },
    { "wastelander", "Import/Export" },
    { "weevil", "Cayo Perico Heist" },
    { "weevil2", "The Criminal Enterprises" },
    { "windsor", "Ill-Gotten Gains Part 1" },
    { "windsor2", "Further Adventures in Finance and Felony" },
    { "winky", "Cayo Perico Heist" },
    { "wolfsbane", "Bikers" },
    { "woodlander", "Money Fronts" },
    { "xa21", "Gunrunning Pack" },
    { "xls", "Further Adventures in Finance and Felony" },
    { "xls2", "Further Adventures in Finance and Felony" },
    { "xtreme", "A Safehouse in the Hills" },
    { "yosemite", "The Doomsday Heist" },
    { "yosemite1500", "Bottom Dollar Bounties" },
    { "yosemite2", "Diamond Casino Heist" },
    { "yosemite3", "LS Summer Special" },
    { "youga", "Game Launch" },
    { "youga2", "Bikers" },
    { "youga3", "LS Summer Special" },
    { "youga4", "The Contract" },
    { "youga5", "Agents of Sabotage" },
    { "z190", "The Doomsday Heist" },
    { "zeno", "The Contract" },
    { "zentorno", "High Life" },
    { "zhaba", "Diamond Casino Heist" },
    { "zion", "Game Launch" },
    { "zion2", "Game Launch" },
    { "zion3", "Diamond Casino & Resort" },
    { "zombiea", "Bikers" },
    { "zombieb", "Bikers" },
    { "zorrusso", "Diamond Casino & Resort" },
    { "zr350", "LS Tuners" },
    { "zr380", "Arena War" },
    { "zr3802", "Arena War" },
    { "zr3803", "Arena War" },
    { "ztype", "Game Launch" },
};

const size_t g_VehicleCount = 935;
