#pragma once
#include "Util/Joaat.hpp"
#include <array>

namespace Stand
{
	struct WeaponComponent
	{
		joaat_t hash;
		const char* display_name;
	};

	inline constexpr WeaponComponent g_weapon_components[] = {
		{ "component_knife_varmod_xm3"_J, "Eyes" },
		{ "component_knife_varmod_xm3_01"_J, "Spatter" },
		{ "component_knife_varmod_xm3_02"_J, "Flames" },
		{ "component_knife_varmod_xm3_03"_J, "Lightning" },
		{ "component_knife_varmod_xm3_04"_J, "Pills" },
		{ "component_knife_varmod_xm3_05"_J, "Snakeskin" },
		{ "component_knife_varmod_xm3_06"_J, "Lucha Libre" },
		{ "component_knife_varmod_xm3_07"_J, "Trippy" },
		{ "component_knife_varmod_xm3_08"_J, "Tequilya" },
		{ "component_knife_varmod_xm3_09"_J, "Orang-O-Tang" },
		{ "component_bat_varmod_xm3"_J, "Blagueurs" },
		{ "component_bat_varmod_xm3_01"_J, "Spatter" },
		{ "component_bat_varmod_xm3_02"_J, "Bullet Holes" },
		{ "component_bat_varmod_xm3_03"_J, "Burger Shot" },
		{ "component_bat_varmod_xm3_04"_J, "Cluckin' Bell" },
		{ "component_bat_varmod_xm3_05"_J, "Fatal Incursion" },
		{ "component_bat_varmod_xm3_06"_J, "Lucha Libre" },
		{ "component_bat_varmod_xm3_07"_J, "Trippy" },
		{ "component_bat_varmod_xm3_08"_J, "Tie-Dye" },
		{ "component_bat_varmod_xm3_09"_J, "Wall" },
		{ "component_pistol_clip_01"_J, "Default Clip" },
		{ "component_pistol_clip_02"_J, "Extended Clip" },
		{ "component_at_pi_flsh"_J, "Flashlight" },
		{ "component_at_pi_supp_02"_J, "Suppressor" },
		{ "component_pistol_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_combatpistol_clip_01"_J, "Default Clip" },
		{ "component_combatpistol_clip_02"_J, "Extended Clip" },
		{ "component_at_pi_supp"_J, "Suppressor" },
		{ "component_combatpistol_varmod_lowrider"_J, "Yusuf Amir Luxury Finish" },
		{ "component_appistol_clip_01"_J, "Default Clip" },
		{ "component_appistol_clip_02"_J, "Extended Clip" },
		{ "component_appistol_varmod_luxe"_J, "Gilded Gun Metal Finish" },
		{ "component_appistol_varmod_security"_J, "Record A Finish" },
		{ "component_pistol50_clip_01"_J, "Default Clip" },
		{ "component_pistol50_clip_02"_J, "Extended Clip" },
		{ "component_at_ar_supp_02"_J, "Suppressor" },
		{ "component_pistol50_varmod_luxe"_J, "Platinum Pearl Deluxe Finish" },
		{ "component_microsmg_clip_01"_J, "Default Clip" },
		{ "component_microsmg_clip_02"_J, "Extended Clip" },
		{ "component_at_scope_macro"_J, "Scope" },
		{ "component_microsmg_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_microsmg_varmod_security"_J, "Organics Finish" },
		{ "component_microsmg_varmod_xm3"_J, "Dildodude Camo" },
		{ "component_smg_clip_01"_J, "Default Clip" },
		{ "component_smg_clip_02"_J, "Extended Clip" },
		{ "component_smg_clip_03"_J, "Drum Magazine" },
		{ "component_at_ar_flsh"_J, "Flashlight" },
		{ "component_at_scope_macro_02"_J, "Scope" },
		{ "component_smg_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_assaultsmg_clip_01"_J, "Default Clip" },
		{ "component_assaultsmg_clip_02"_J, "Extended Clip" },
		{ "component_assaultsmg_varmod_lowrider"_J, "Yusuf Amir Luxury Finish" },
		{ "component_assaultrifle_clip_01"_J, "Default Clip" },
		{ "component_assaultrifle_clip_02"_J, "Extended Clip" },
		{ "component_assaultrifle_clip_03"_J, "Drum Magazine" },
		{ "component_at_ar_afgrip"_J, "Grip" },
		{ "component_assaultrifle_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_carbinerifle_clip_01"_J, "Default Clip" },
		{ "component_carbinerifle_clip_02"_J, "Extended Clip" },
		{ "component_carbinerifle_clip_03"_J, "Box Magazine" },
		{ "component_at_railcover_01"_J, "COMPONENT_AT_RAILCOVER_01" },
		{ "component_at_scope_medium"_J, "Scope" },
		{ "component_at_ar_supp"_J, "Suppressor" },
		{ "component_carbinerifle_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_advancedrifle_clip_01"_J, "Default Clip" },
		{ "component_advancedrifle_clip_02"_J, "Extended Clip" },
		{ "component_at_scope_small"_J, "Scope" },
		{ "component_advancedrifle_varmod_luxe"_J, "Gilded Gun Metal Finish" },
		{ "component_mg_clip_01"_J, "Default Clip" },
		{ "component_mg_clip_02"_J, "Extended Clip" },
		{ "component_at_scope_small_02"_J, "Scope" },
		{ "component_mg_varmod_lowrider"_J, "Yusuf Amir Luxury Finish" },
		{ "component_combatmg_clip_01"_J, "Default Clip" },
		{ "component_combatmg_clip_02"_J, "Extended Clip" },
		{ "component_combatmg_varmod_lowrider"_J, "Etched Gun Metal Finish" },
		{ "component_at_sr_supp"_J, "Suppressor" },
		{ "component_pumpshotgun_varmod_lowrider"_J, "Yusuf Amir Luxury Finish" },
		{ "component_pumpshotgun_varmod_security"_J, "Bone Finish" },
		{ "component_pumpshotgun_varmod_xm3"_J, "Dildodude Camo" },
		{ "component_sawnoffshotgun_varmod_luxe"_J, "Gilded Gun Metal Finish" },
		{ "component_assaultshotgun_clip_01"_J, "Default Clip" },
		{ "component_assaultshotgun_clip_02"_J, "Extended Clip" },
		{ "component_sniperrifle_clip_01"_J, "Default Clip" },
		{ "component_at_scope_large"_J, "Scope" },
		{ "component_at_scope_max"_J, "Advanced Scope" },
		{ "component_sniperrifle_varmod_luxe"_J, "Etched Wood Grip Finish" },
		{ "component_heavysniper_clip_01"_J, "Default Clip" },
		{ "component_minigun_clip_01"_J, "Extended Clip" },
		{ "police_torch_flashlight"_J, "Flashlight" },
		{ "component_snspistol_clip_01"_J, "Default Clip" },
		{ "component_snspistol_clip_02"_J, "Extended Clip" },
		{ "component_snspistol_varmod_lowrider"_J, "Etched Wood Grip Finish" },
		{ "component_bullpuprifle_clip_01"_J, "Default Clip" },
		{ "component_bullpuprifle_clip_02"_J, "Extended Clip" },
		{ "component_bullpuprifle_varmod_low"_J, "Gilded Gun Metal Finish" },
		{ "component_specialcarbine_clip_01"_J, "Default Clip" },
		{ "component_specialcarbine_clip_02"_J, "Extended Clip" },
		{ "component_specialcarbine_clip_03"_J, "Drum Magazine" },
		{ "component_specialcarbine_varmod_lowrider"_J, "Etched Gun Metal Finish" },
		{ "component_heavypistol_clip_01"_J, "Default Clip" },
		{ "component_heavypistol_clip_02"_J, "Extended Clip" },
		{ "component_heavypistol_varmod_luxe"_J, "Etched Wood Grip Finish" },
		{ "component_bullpuprifle_mk2_clip_01"_J, "Default Clip" },
		{ "component_bullpuprifle_mk2_clip_02"_J, "Extended Clip" },
		{ "component_bullpuprifle_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_bullpuprifle_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_bullpuprifle_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_bullpuprifle_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_at_sights"_J, "Holographic Sight" },
		{ "component_at_scope_macro_02_mk2"_J, "Small Scope" },
		{ "component_at_scope_small_mk2"_J, "Medium Scope" },
		{ "component_at_bp_barrel_01"_J, "Default Barrel" },
		{ "component_at_bp_barrel_02"_J, "Heavy Barrel" },
		{ "component_at_muzzle_01"_J, "Flat Muzzle Brake" },
		{ "component_at_muzzle_02"_J, "Tactical Muzzle Brake" },
		{ "component_at_muzzle_03"_J, "Fat-End Muzzle Brake" },
		{ "component_at_muzzle_04"_J, "Precision Muzzle Brake" },
		{ "component_at_muzzle_05"_J, "Heavy Duty Muzzle Brake" },
		{ "component_at_muzzle_06"_J, "Slanted Muzzle Brake" },
		{ "component_at_muzzle_07"_J, "Split-End Muzzle Brake" },
		{ "component_at_ar_afgrip_02"_J, "Grip" },
		{ "component_marksmanrifle_mk2_clip_01"_J, "Default Clip" },
		{ "component_marksmanrifle_mk2_clip_02"_J, "Extended Clip" },
		{ "component_marksmanrifle_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_marksmanrifle_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_marksmanrifle_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_marksmanrifle_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_scope_medium_mk2"_J, "Large Scope" },
		{ "component_at_scope_large_fixed_zoom_mk2"_J, "Zoom Scope" },
		{ "component_at_mrfl_barrel_01"_J, "Default Barrel" },
		{ "component_at_mrfl_barrel_02"_J, "Heavy Barrel" },
		{ "component_pistolxm3_clip_01"_J, "Default Clip" },
		{ "component_pistolxm3_supp"_J, "Suppressor" },
		{ "component_specialcarbine_mk2_clip_01"_J, "Default Clip" },
		{ "component_specialcarbine_mk2_clip_02"_J, "Extended Clip" },
		{ "component_specialcarbine_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_specialcarbine_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_specialcarbine_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_specialcarbine_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_at_scope_macro_mk2"_J, "Small Scope" },
		{ "component_at_sc_barrel_01"_J, "Default Barrel" },
		{ "component_at_sc_barrel_02"_J, "Heavy Barrel" },
		{ "component_snspistol_mk2_clip_01"_J, "Default Clip" },
		{ "component_snspistol_mk2_clip_02"_J, "Extended Clip" },
		{ "component_snspistol_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_snspistol_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_snspistol_mk2_clip_hollowpoint"_J, "Hollow Point Rounds" },
		{ "component_snspistol_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_at_pi_flsh_03"_J, "Flashlight" },
		{ "component_at_pi_rail_02"_J, "Mounted Scope" },
		{ "component_at_pi_comp_02"_J, "Compensator" },
		{ "component_pumpshotgun_mk2_clip_01"_J, "Default Shells" },
		{ "component_pumpshotgun_mk2_clip_armorpiercing"_J, "Steel Buckshot Shells" },
		{ "component_pumpshotgun_mk2_clip_explosive"_J, "Explosive Slugs" },
		{ "component_pumpshotgun_mk2_clip_hollowpoint"_J, "Flechette Shells" },
		{ "component_pumpshotgun_mk2_clip_incendiary"_J, "Dragon's Breath Shells" },
		{ "component_at_sr_supp_03"_J, "Suppressor" },
		{ "component_at_muzzle_08"_J, "Muzzle Brake" },
		{ "component_railgunxm3_clip_01"_J, "Default Clip" },
		{ "component_raypistol_varmod_xmas18"_J, "Festive tint" },
		{ "component_revolver_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_revolver_mk2_clip_hollowpoint"_J, "Hollow Point Rounds" },
		{ "component_revolver_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_revolver_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_pi_comp_03"_J, "Compensator" },
		{ "component_doubleaction_clip_01"_J, "Default Clip" },
		{ "component_gusenberg_clip_01"_J, "Default Clip" },
		{ "component_gusenberg_clip_02"_J, "Extended Clip" },
		{ "component_vintagepistol_clip_01"_J, "Default Clip" },
		{ "component_vintagepistol_clip_02"_J, "Extended Clip" },
		{ "component_railgun_clip_01"_J, "Default Clip" },
		{ "component_heavyshotgun_clip_01"_J, "Default Clip" },
		{ "component_heavyshotgun_clip_02"_J, "Extended Clip" },
		{ "component_heavyshotgun_clip_03"_J, "Drum Magazine" },
		{ "component_marksmanrifle_clip_01"_J, "Default Clip" },
		{ "component_marksmanrifle_clip_02"_J, "Extended Clip" },
		{ "component_at_scope_large_fixed_zoom"_J, "Scope" },
		{ "component_marksmanrifle_varmod_luxe"_J, "Yusuf Amir Luxury Finish" },
		{ "component_ceramicpistol_clip_01"_J, "Default Clip" },
		{ "component_ceramicpistol_clip_02"_J, "Extended Clip" },
		{ "component_ceramicpistol_supp"_J, "Suppressor" },
		{ "component_militaryrifle_clip_01"_J, "Default Clip" },
		{ "component_militaryrifle_clip_02"_J, "Extended Clip" },
		{ "component_militaryrifle_sight_01"_J, "Iron Sights" },
		{ "component_combatshotgun_clip_01"_J, "Default Shells" },
		{ "component_gadgetpistol_clip_01"_J, "Default Clip" },
		{ "component_navyrevolver_clip_01"_J, "Default Clip" },
		{ "component_knuckle_varmod_base"_J, "Base Model" },
		{ "component_knuckle_varmod_pimp"_J, "The Pimp" },
		{ "component_knuckle_varmod_ballas"_J, "The Ballas" },
		{ "component_knuckle_varmod_dollar"_J, "The Hustler" },
		{ "component_knuckle_varmod_diamond"_J, "The Rock" },
		{ "component_knuckle_varmod_hate"_J, "The Hater" },
		{ "component_knuckle_varmod_love"_J, "The Lover" },
		{ "component_knuckle_varmod_player"_J, "The Player" },
		{ "component_knuckle_varmod_king"_J, "The King" },
		{ "component_knuckle_varmod_vagos"_J, "The Vagos" },
		{ "component_combatpdw_clip_01"_J, "Default Clip" },
		{ "component_combatpdw_clip_02"_J, "Extended Clip" },
		{ "component_combatpdw_clip_03"_J, "Drum Magazine" },
		{ "component_marksmanpistol_clip_01"_J, "Default Clip" },
		{ "component_machinepistol_clip_01"_J, "Default Clip" },
		{ "component_machinepistol_clip_02"_J, "Extended Clip" },
		{ "component_machinepistol_clip_03"_J, "Drum Magazine" },
		{ "component_compactrifle_clip_01"_J, "Default Clip" },
		{ "component_compactrifle_clip_02"_J, "Extended Clip" },
		{ "component_compactrifle_clip_03"_J, "Drum Magazine" },
		{ "component_switchblade_varmod_base"_J, "Default Handle" },
		{ "component_switchblade_varmod_var1"_J, "VIP Variant" },
		{ "component_switchblade_varmod_var2"_J, "Bodyguard Variant" },
		{ "component_revolver_clip_01"_J, "Default Clip" },
		{ "component_revolver_varmod_boss"_J, "VIP Variant" },
		{ "component_revolver_varmod_goon"_J, "Bodyguard Variant" },
		{ "component_compactlauncher_clip_01"_J, "Default Clip" },
		{ "component_minismg_clip_01"_J, "Default Clip" },
		{ "component_minismg_clip_02"_J, "Extended Clip" },
		{ "component_autoshotgun_clip_01"_J, "Default Clip" },
		{ "component_carbinerifle_mk2_clip_01"_J, "Default Clip" },
		{ "component_carbinerifle_mk2_clip_02"_J, "Extended Clip" },
		{ "component_carbinerifle_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_carbinerifle_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_carbinerifle_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_carbinerifle_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_cr_barrel_01"_J, "Default Barrel" },
		{ "component_at_cr_barrel_02"_J, "Heavy Barrel" },
		{ "component_assaultrifle_mk2_clip_01"_J, "Default Clip" },
		{ "component_assaultrifle_mk2_clip_02"_J, "Extended Clip" },
		{ "component_assaultrifle_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_assaultrifle_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_assaultrifle_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_assaultrifle_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_ar_barrel_01"_J, "Default Barrel" },
		{ "component_at_ar_barrel_02"_J, "Heavy Barrel" },
		{ "component_combatmg_mk2_clip_01"_J, "Default Clip" },
		{ "component_combatmg_mk2_clip_02"_J, "Extended Clip" },
		{ "component_combatmg_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_combatmg_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_combatmg_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_combatmg_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_mg_barrel_01"_J, "Default Barrel" },
		{ "component_at_mg_barrel_02"_J, "Heavy Barrel" },
		{ "component_smg_mk2_clip_01"_J, "Default Clip" },
		{ "component_smg_mk2_clip_02"_J, "Extended Clip" },
		{ "component_smg_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_smg_mk2_clip_hollowpoint"_J, "Hollow Point Rounds" },
		{ "component_smg_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_smg_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_sights_smg"_J, "Holographic Sight" },
		{ "component_at_scope_macro_02_smg_mk2"_J, "Small Scope" },
		{ "component_at_scope_small_smg_mk2"_J, "Medium Scope" },
		{ "component_at_sb_barrel_01"_J, "Default Barrel" },
		{ "component_at_sb_barrel_02"_J, "Heavy Barrel" },
		{ "component_heavysniper_mk2_clip_01"_J, "Default Clip" },
		{ "component_heavysniper_mk2_clip_02"_J, "Extended Clip" },
		{ "component_heavysniper_mk2_clip_armorpiercing"_J, "Armor Piercing Rounds" },
		{ "component_heavysniper_mk2_clip_explosive"_J, "Explosive Rounds" },
		{ "component_heavysniper_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_heavysniper_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_at_scope_large_mk2"_J, "Zoom Scope" },
		{ "component_at_scope_nv"_J, "Night Vision Scope" },
		{ "component_at_scope_thermal"_J, "Thermal Scope" },
		{ "component_at_muzzle_09"_J, "Muzzle Brake" },
		{ "component_at_sr_barrel_01"_J, "Default Barrel" },
		{ "component_at_sr_barrel_02"_J, "Heavy Barrel" },
		{ "component_pistol_mk2_clip_01"_J, "Default Clip" },
		{ "component_pistol_mk2_clip_02"_J, "Extended Clip" },
		{ "component_pistol_mk2_clip_fmj"_J, "Full Metal Jacket Rounds" },
		{ "component_pistol_mk2_clip_hollowpoint"_J, "Hollow Point Rounds" },
		{ "component_pistol_mk2_clip_incendiary"_J, "Incendiary Rounds" },
		{ "component_pistol_mk2_clip_tracer"_J, "Tracer Rounds" },
		{ "component_at_pi_rail"_J, "Mounted Scope" },
		{ "component_at_pi_flsh_02"_J, "Flashlight" },
		{ "component_at_pi_comp"_J, "Compensator" },
		{ "component_pistol_mk2_varmod_xm3"_J, "Season's Greetings" },
		{ "component_tacticalrifle_clip_01"_J, "Default Clip" },
		{ "component_tacticalrifle_clip_02"_J, "Extended Clip" },
		{ "component_at_ar_flsh_reh"_J, "Flashlight" },
		{ "component_precisionrifle_clip_01"_J, "Default Clip" },
		{ "component_heavyrifle_clip_01"_J, "Default Clip" },
		{ "component_heavyrifle_clip_02"_J, "Extended Clip" },
		{ "component_emplauncher_clip_01"_J, "Default Clip" },
		{ "component_tecpistol_clip_01"_J, "Default Clip" },
		{ "component_tecpistol_clip_02"_J, "Extended Clip" },
		{ "component_battlerifle_clip_01"_J, "Default Clip" },
		{ "component_battlerifle_clip_02"_J, "Extended Clip" },
		{ "component_rpg_varmod_tvr"_J, "Uncle T Finish" },
		{ "component_microsmg_varmod_frn"_J, "Employee of the Month Finish" },
		{ "component_carbinerifle_varmod_mich"_J, "Suede Bucks Finish" },
		{ "component_combatpistol_varmod_xmas23"_J, "Snowman Finish" },
		{ "component_specialcarbine_varmod_xmas23"_J, "Skull Santa Finish" },
		{ "component_heavysniper_varmod_xmas23"_J, "Santa's Helper Finish" },
		{ "component_stungun_varmod_bail"_J, "Bottom Dollar Bail Enforcement" },
		{ "component_pumpshotgun_clip_01"_J, "COMPONENT_PUMPSHOTGUN_CLIP_01" },
		{ "component_sawnoffshotgun_clip_01"_J, "COMPONENT_SAWNOFFSHOTGUN_CLIP_01" },
		{ "component_bullpupshotgun_clip_01"_J, "COMPONENT_BULLPUPSHOTGUN_CLIP_01" },
		{ "component_grenadelauncher_clip_01"_J, "COMPONENT_GRENADELAUNCHER_CLIP_01" },
		{ "component_rpg_clip_01"_J, "COMPONENT_RPG_CLIP_01" },
		{ "component_revolver_mk2_clip_01"_J, "COMPONENT_REVOLVER_MK2_CLIP_01" },
		{ "component_hominglauncher_clip_01"_J, "COMPONENT_HOMINGLAUNCHER_CLIP_01" },
		{ "component_firework_clip_01"_J, "COMPONENT_FIREWORK_CLIP_01" },
		{ "component_musket_clip_01"_J, "COMPONENT_MUSKET_CLIP_01" },
		{ "component_flaregun_clip_01"_J, "COMPONENT_FLAREGUN_CLIP_01" },
		{ "component_dbshotgun_clip_01"_J, "COMPONENT_DBSHOTGUN_CLIP_01" },
		{ "component_pistol_mk2_varmod_xm3_slide"_J, "COMPONENT_PISTOL_MK2_VARMOD_XM3_SLIDE" },
		{ "component_heavyrifle_sight_01"_J, "COMPONENT_HEAVYRIFLE_SIGHT_01" },
		{ "component_revolver_mk2_camo"_J, "Digital Camo" },
		{ "component_revolver_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_revolver_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_revolver_mk2_camo_04"_J, "Skull" },
		{ "component_revolver_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_revolver_mk2_camo_06"_J, "Perseus" },
		{ "component_revolver_mk2_camo_07"_J, "Leopard" },
		{ "component_revolver_mk2_camo_08"_J, "Zebra" },
		{ "component_revolver_mk2_camo_09"_J, "Geometric" },
		{ "component_revolver_mk2_camo_10"_J, "Boom!" },
		{ "component_revolver_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_assaultrifle_mk2_camo"_J, "Digital Camo" },
		{ "component_assaultrifle_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_assaultrifle_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_assaultrifle_mk2_camo_04"_J, "Skull" },
		{ "component_assaultrifle_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_assaultrifle_mk2_camo_06"_J, "Perseus" },
		{ "component_assaultrifle_mk2_camo_07"_J, "Leopard" },
		{ "component_assaultrifle_mk2_camo_08"_J, "Zebra" },
		{ "component_assaultrifle_mk2_camo_09"_J, "Geometric" },
		{ "component_assaultrifle_mk2_camo_10"_J, "Boom!" },
		{ "component_assaultrifle_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_pistol_mk2_camo_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_02_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_03_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_04_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_05_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_06_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_07_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_08_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_09_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_10_slide"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_ind_01_slide"_J, "Patriotic" },
		{ "component_pistol_mk2_camo"_J, "Digital Camo" },
		{ "component_pistol_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_pistol_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_pistol_mk2_camo_04"_J, "Skull" },
		{ "component_pistol_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_pistol_mk2_camo_06"_J, "Perseus" },
		{ "component_pistol_mk2_camo_07"_J, "Leopard" },
		{ "component_pistol_mk2_camo_08"_J, "Zebra" },
		{ "component_pistol_mk2_camo_09"_J, "Geometric" },
		{ "component_pistol_mk2_camo_10"_J, "Boom!" },
		{ "component_pistol_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_pumpshotgun_mk2_camo"_J, "Digital Camo" },
		{ "component_pumpshotgun_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_pumpshotgun_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_pumpshotgun_mk2_camo_04"_J, "Skull" },
		{ "component_pumpshotgun_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_pumpshotgun_mk2_camo_06"_J, "Perseus" },
		{ "component_pumpshotgun_mk2_camo_07"_J, "Leopard" },
		{ "component_pumpshotgun_mk2_camo_08"_J, "Zebra" },
		{ "component_pumpshotgun_mk2_camo_09"_J, "Geometric" },
		{ "component_pumpshotgun_mk2_camo_10"_J, "Boom!" },
		{ "component_pumpshotgun_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_marksmanrifle_mk2_camo"_J, "Digital Camo" },
		{ "component_marksmanrifle_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_marksmanrifle_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_marksmanrifle_mk2_camo_04"_J, "Skull" },
		{ "component_marksmanrifle_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_marksmanrifle_mk2_camo_06"_J, "Perseus" },
		{ "component_marksmanrifle_mk2_camo_07"_J, "Leopard" },
		{ "component_marksmanrifle_mk2_camo_08"_J, "Zebra" },
		{ "component_marksmanrifle_mk2_camo_09"_J, "Geometric" },
		{ "component_marksmanrifle_mk2_camo_10"_J, "Boom!" },
		{ "component_marksmanrifle_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_heavysniper_mk2_camo"_J, "Digital Camo" },
		{ "component_heavysniper_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_heavysniper_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_heavysniper_mk2_camo_04"_J, "Skull" },
		{ "component_heavysniper_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_heavysniper_mk2_camo_06"_J, "Perseus" },
		{ "component_heavysniper_mk2_camo_07"_J, "Leopard" },
		{ "component_heavysniper_mk2_camo_08"_J, "Zebra" },
		{ "component_heavysniper_mk2_camo_09"_J, "Geometric" },
		{ "component_heavysniper_mk2_camo_10"_J, "Boom!" },
		{ "component_heavysniper_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_combatmg_mk2_camo"_J, "Digital Camo" },
		{ "component_combatmg_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_combatmg_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_combatmg_mk2_camo_04"_J, "Skull" },
		{ "component_combatmg_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_combatmg_mk2_camo_06"_J, "Perseus" },
		{ "component_combatmg_mk2_camo_07"_J, "Leopard" },
		{ "component_combatmg_mk2_camo_08"_J, "Zebra" },
		{ "component_combatmg_mk2_camo_09"_J, "Geometric" },
		{ "component_combatmg_mk2_camo_10"_J, "Boom!" },
		{ "component_combatmg_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_smg_mk2_camo"_J, "Digital Camo" },
		{ "component_smg_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_smg_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_smg_mk2_camo_04"_J, "Skull" },
		{ "component_smg_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_smg_mk2_camo_06"_J, "Perseus" },
		{ "component_smg_mk2_camo_07"_J, "Leopard" },
		{ "component_smg_mk2_camo_08"_J, "Zebra" },
		{ "component_smg_mk2_camo_09"_J, "Geometric" },
		{ "component_smg_mk2_camo_10"_J, "Boom!" },
		{ "component_smg_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_bullpuprifle_mk2_camo"_J, "Digital Camo" },
		{ "component_bullpuprifle_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_bullpuprifle_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_bullpuprifle_mk2_camo_04"_J, "Skull" },
		{ "component_bullpuprifle_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_bullpuprifle_mk2_camo_06"_J, "Perseus" },
		{ "component_bullpuprifle_mk2_camo_07"_J, "Leopard" },
		{ "component_bullpuprifle_mk2_camo_08"_J, "Zebra" },
		{ "component_bullpuprifle_mk2_camo_09"_J, "Geometric" },
		{ "component_bullpuprifle_mk2_camo_10"_J, "Boom!" },
		{ "component_bullpuprifle_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_specialcarbine_mk2_camo"_J, "Digital Camo" },
		{ "component_specialcarbine_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_specialcarbine_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_specialcarbine_mk2_camo_04"_J, "Skull" },
		{ "component_specialcarbine_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_specialcarbine_mk2_camo_06"_J, "Perseus" },
		{ "component_specialcarbine_mk2_camo_07"_J, "Leopard" },
		{ "component_specialcarbine_mk2_camo_08"_J, "Zebra" },
		{ "component_specialcarbine_mk2_camo_09"_J, "Geometric" },
		{ "component_specialcarbine_mk2_camo_10"_J, "Boom!" },
		{ "component_specialcarbine_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_heavyrifle_camo1"_J, "Digital Camo" },
		{ "component_carbinerifle_mk2_camo"_J, "Digital Camo" },
		{ "component_carbinerifle_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_carbinerifle_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_carbinerifle_mk2_camo_04"_J, "Skull" },
		{ "component_carbinerifle_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_carbinerifle_mk2_camo_06"_J, "Perseus" },
		{ "component_carbinerifle_mk2_camo_07"_J, "Leopard" },
		{ "component_carbinerifle_mk2_camo_08"_J, "Zebra" },
		{ "component_carbinerifle_mk2_camo_09"_J, "Geometric" },
		{ "component_carbinerifle_mk2_camo_10"_J, "Boom!" },
		{ "component_carbinerifle_mk2_camo_ind_01"_J, "Patriotic" },
		{ "component_snspistol_mk2_camo_slide"_J, "Digital Camo" },
		{ "component_snspistol_mk2_camo_02_slide"_J, "Brushstroke Camo" },
		{ "component_snspistol_mk2_camo_03_slide"_J, "Woodland Camo" },
		{ "component_snspistol_mk2_camo_04_slide"_J, "Skull" },
		{ "component_snspistol_mk2_camo_05_slide"_J, "Sessanta Nove" },
		{ "component_snspistol_mk2_camo_06_slide"_J, "Perseus" },
		{ "component_snspistol_mk2_camo_07_slide"_J, "Leopard" },
		{ "component_snspistol_mk2_camo_08_slide"_J, "Zebra" },
		{ "component_snspistol_mk2_camo_09_slide"_J, "Geometric" },
		{ "component_snspistol_mk2_camo_10_slide"_J, "Boom!" },
		{ "component_snspistol_mk2_camo_ind_01_slide"_J, "Patriotic" },
		{ "component_snspistol_mk2_camo"_J, "Digital Camo" },
		{ "component_snspistol_mk2_camo_02"_J, "Brushstroke Camo" },
		{ "component_snspistol_mk2_camo_03"_J, "Woodland Camo" },
		{ "component_snspistol_mk2_camo_04"_J, "Skull" },
		{ "component_snspistol_mk2_camo_05"_J, "Sessanta Nove" },
		{ "component_snspistol_mk2_camo_06"_J, "Perseus" },
		{ "component_snspistol_mk2_camo_07"_J, "Leopard" },
		{ "component_snspistol_mk2_camo_08"_J, "Zebra" },
		{ "component_snspistol_mk2_camo_09"_J, "Geometric" },
		{ "component_snspistol_mk2_camo_10"_J, "Boom!" },
		{ "component_snspistol_mk2_camo_ind_01"_J, "Patriotic" },
	};
}
